function getData(){
	const keysw = "www.tipswalls.com";
	var keyAPI = (typeof keyhost != 'undefined') ? keyhost : document.location.host;
	var dataAMZ = {};
	if(keysw == keyAPI){
		dataAMZ = {
			B01ALBMIEI: {href: "https://amzn.to/2NYOlUT",nameProduct: `Giantex Portable Mini Compact Twin Tub Washing Machine 17.6lbs Washer Spain Spinner, Blue+ White`,slug: ""},
			B01KIMOEW4: {href: "https://amzn.to/36vy3ZS",nameProduct: `Hoover Spotless Portable Carpet & Upholstery Spot Cleaner, FH11300PC`,slug: ""},
			B07NHVFWCQ: {href: "https://amzn.to/3oBGskN",nameProduct: `Panda Full-Automatic Portable Machine, 1.34 Cu.ft,10lbs Capacity, Light Gray, PAN56MGP3, 10 Wash Programs, Compact Top Load Cloth Washer`,slug: ""},
			B078HFRNPQ: {href: "https://amzn.to/3rf8ioW",nameProduct: `Blackstone 1825 36" Accessory Griddle with Side Shelf, 36 inch-4 Burner-W/New`,slug: ""},
			B07B94ZR74: {href: "https://amzn.to/36xsQke",nameProduct: `SUPER DEAL Portable Compact Mini Twin Tub Washing Machine w/Wash and Spin Cycle, Built-in Gravity Drain, 13lbs Capacity For Camping, Apartments, Dorms, College Rooms, RV’s, Delicates and more`,slug: ""},
			B07BD2G4TY: {href: "https://amzn.to/3apx9zl",nameProduct: `ZENY Portable Mini Twin Tub Washing Machine 13lbs Capacity with Spin Dryer,Compact Cloths Washing Machine Lightweight Small Laundry Washer for Home,Apartments, Dorm Rooms,RV's`,slug: ""},
			B0028AYQDC: {href: "https://amzn.to/3pEOz1b",nameProduct: `Whynter ARC-14S 14,000 BTU Dual Hose Portable Air Conditioner, Dehumidifier, Fan with Activated Carbon Filter Plus Storage Bag for Rooms up to 500 sq ft, Platinum and Black`,slug: ""},
			B000BQMV0A: {href: "https://amzn.to/3rcZDmN",nameProduct: `Reflectix DW1202504 Spiral Duct Wrap, Silver`,slug: ""},
			B000BQRBB4: {href: "https://amzn.to/36Pcy6P",nameProduct: `Reflectix FT210 Reflective Foil Tape, 2" x 30'`,slug: ""},
			B01ICBLBL0: {href: "https://amzn.to/3pF1dgU",nameProduct: `Best Choice Products Portable Compact Mini Twin Tub Laundry Washing Machine and Spin Cycle Dryer w/Hose, 13lbs Load Capacity, Built-In Drain - White/Blue`,slug: ""},
			B07C76PV28: {href: "https://amzn.to/3rgE0ll",nameProduct: `Honeywell MO10CESWK Compact 3-in-1 Portable Air Conditioner w/ Remote Control, Up to 450 Sq. Ft., White/Black`,slug: ""},
			B07J6S4RZ9: {href: "https://amzn.to/2NOgVYU",nameProduct: `ZENY Portable Compact Washing Machine Mini Twin Tub Washer Spin Spinner 9.9lbs Capacity, Lightweight Small Laundry Washer for Apartment RV`,slug: ""},
			B079BZHVGV: {href: "https://amzn.to/2YCr2SJ",nameProduct: `Lemi Shine 100% Natural Citric Extracts Laundry Detergent Booster Liquid, 3-Bottles of 32 fl oz`,slug: ""},
			B085NYQ9ZC: {href: "https://amzn.to/3ctCngc",nameProduct: `Honeywell, MN12CEDWW 12,000 BTU Air Portable Conditioner with Dual Hose, 12000, White`,slug: ""},
			B07NBKGNJ2: {href: "https://amzn.to/36xmCkK",nameProduct: `KUPPET Portable Compact Mini Washing Machine,Twin Tub 26.4 lbs Capacity,Washer(17.6lbs)&Spiner(8.8lbs),Built-in Drain Pump/Semi-Automatic，(White&Blue)`,slug: ""},
			B07TDP2MMQ: {href: "https://amzn.to/3pGF8yj",nameProduct: `KUPPET Compact Twin Tub Portable Mini Washing Machine 26lbs Capacity, Washer(18lbs)&Spiner(8lbs)/Built-in Drain Pump/Semi-Automatic (White&Gray)`,slug: ""},
			B071RZXXZ9: {href: "https://amzn.to/3j8XZjb",nameProduct: `Philips Norelco MG5750/49 Multigroom All-In-One Trimmer Series 5000 With 18Piece, No Blade Oil Needed,`,slug: ""},
			B01DTYAZO4: {href: "https://amzn.to/3j6aiwC",nameProduct: `BISSELL Crosswave All in One Wet Dry Vacuum Cleaner and Mop for Hard Floors and Area Rugs, 1785A, Green`,slug: ""},
			B07144LZ9V: {href: "https://amzn.to/3tkmO06",nameProduct: `Best Choice Products Portable Mini Twin Tub Compact Washing Machine and Dryer Combo, 18-Pound Load Capacity, w/ 15-Minute Timer, Drain Hose, Spin Dry Cycle, White/Blue`,slug: ""},
			B06WP2CLYY: {href: "https://amzn.to/3r8SbJp",nameProduct: `BISSELL Spinwave Powered Hardwood Floor Mop and Cleaner, Green Spinwave`,slug: ""},
			B07238W469: {href: "https://amzn.to/3rhJTyZ",nameProduct: `JHS 12,000 BTU Portable Air Conditioner, 3-in-1 Floor AC Unit with 3 Fan Speeds, Remote Control and Digital LED Display, Cover up to 400 Sq. Ft.`,slug: ""},
			B07PW66ZSN: {href: "https://amzn.to/3rb5QzB",nameProduct: `COLZER 140 Pints Commercial Dehumidifier Large Capacity Dehumidifiers for Basements, Showrooms, Gallery, Storage Rooms, Warehouse, Build-in 17-Pint Water Tank and 6.6 ft. Drain Hose`,slug: ""},
			B07MXDRTKJ: {href: "https://amzn.to/2MfU48r",nameProduct: `COLZER 70 Pints Home Dehumidifiers for 4,500 SQ FT Basements & Large Rooms, Large Removal Capacity with 7.4-Pint Water Bucket & Continuous Drain Hose for Self-draining`,slug: ""},
			B07Q55RYK8: {href: "https://amzn.to/2MLSQkU",nameProduct: `Inofia Air Purifier With True HEPA Air Filter, Wi-Fi Intelligent Control, Air Cleaner For Large Room, For Spaces Up To 1056 Sq Ft, Dust, Smoke, Pets dander, Smokers, Perfect For Home/Office`,slug: ""},
			B06XKDYD4S: {href: "https://amzn.to/3akcP2m",nameProduct: `Giantex 16lbs Portable Mini Washing Machine Gravity Drain Compact Twin Tub Washer Spinner, Ideal for Dorms, Apartments, RVs, Camping`,slug: ""},
			B07V56QH7T: {href: "https://amzn.to/2MiLvK2",nameProduct: `Hathaspace Smart True HEPA Air Purifier 2.0 for Extra-Large Rooms with Medical Grade H13 HEPA Filter, 5-in-1 Home Air Cleaner for Allergies, Asthma, Pets, Odors, Smokers, 1500+ Sq Ft Coverage - HSP002`,slug: ""},
			B00Q8M0NWE: {href: "https://amzn.to/3r4GTWy",nameProduct: `Dolphin Nautilus CC Plus Automatic Robotic Pool Cleaner with Easy To Clean Large Top Load Filter Cartridges and Tangle-Free Swivel Cord, Ideal for In-Ground Swimming Pools Up To 50 Feet`,slug: ""},
			B01N3CCOZ3: {href: "https://amzn.to/3cy8HhY",nameProduct: `Leesa Luxury Hybrid 11 Inch Mattress, Innerspring and Premium Foam, King`,slug: ""},
			B076MJFKVG: {href: "https://amzn.to/36xxj6x",nameProduct: `Brooklyn Signature 11" Hybrid Mattress with Patented TitanFlex Pressure Relieving Foam, Queen Medium`,slug: ""},
			B0876HX533: {href: "https://amzn.to/3jjBbO1",nameProduct: `The Purple Mattress (Queen)`,slug: ""},
			B0889GW1VP: {href: "https://amzn.to/3pGdFwX",nameProduct: `Nectar Full Mattress - 365 Night Home Trial - Gel Memory Foam Mattress - CertiPUR-US Certified Foams - Forever Warranty`,slug: ""},
			B00RDITBSY: {href: "https://amzn.to/3tewolk",nameProduct: `Leesa Original Bed-in-a-Box, Three Premium Foam Layers Mattress, King, Gray & White`,slug: ""},
			B079TGL2BZ: {href: "https://amzn.to/3ra4Njq",nameProduct: `Acer Aspire E 15, 15.6" Full HD, 8th Gen Intel Core i3-8130U, 6GB RAM Memory, 1TB HDD, 8X DVD, E5-576-392H`,slug: ""},
			B00G7RHGNY: {href: "https://amzn.to/3rbYKL9",nameProduct: `PowerBlock Elite Dumbbells`,slug: ""},
			B01MRNXXYQ: {href: "https://amzn.to/3cy97VA",nameProduct: `Sunny Health & Fitness Folding Compact Motorized Treadmill - LCD Display, Shock Absorption and 220 LB Max Weight - SF-T7632,Gray`,slug: ""},
			B001G60JA8: {href: "https://amzn.to/39ImiBH",nameProduct: `SOLE F63 Treadmill`,slug: ""},
			B075VCM1XR: {href: "https://amzn.to/3cuYrqP",nameProduct: `ZINUS Dori Upholstered Platform Bed Frame with Wingback Headboard / Mattress Foundation / Wood Slat Support / No Box Spring Needed / Easy Assembly, Queen`,slug: ""},
			B00PQA3GX2: {href: "https://amzn.to/3asDJ8n",nameProduct: `Safavieh Hudson Shag Collection SGH280A Moroccan Ogee 2-inch Thick Area Rug, 2' x 3', Ivory/Grey`,slug: ""},
			B01M7X9PIG: {href: "https://amzn.to/3cuYAKT",nameProduct: `WARN 96815 VR10-S Electric 12V Winch with Synthetic Rope: 3/8" Diameter x 90' Length, 5 Ton (10,000 lb) Pulling Capacity`,slug: ""},
			B07BQL8L1K: {href: "https://amzn.to/3cucPiT",nameProduct: `Zinus Benton, Sofa, Stone Grey`,slug: ""},
			B07F2H3NL8: {href: "https://amzn.to/2YDpJ5W",nameProduct: `Woodbridge 59" Acrylic Freestanding Bathtub Contemporary Soaking Tub with Brushed Nickel Overflow and Drain, Oval`,slug: ""},
			B06XMY9D5K: {href: "https://amzn.to/3pIJchF",nameProduct: `Zinus Paul Metal and Wood Platform Bed with Wood Slat Support, Queen`,slug: ""},
			B016J0EITS: {href: "https://amzn.to/3cuZ0AX",nameProduct: `SureFire X300 Ultra Series LED WeaponLights with TIR Lens`,slug: ""},
			B07GZN3QNZ: {href: "https://amzn.to/3aqdHSZ",nameProduct: `Inofia 8 inch Hybrid Comfort Eurotop Innerspring Mattress- Plush Yet Supportive-Pressure Relief, Twin Size`,slug: ""},
			B01MXNLIET: {href: "https://amzn.to/3tpOGQT",nameProduct: `Reverie 5 Series Adjustable Bed, Wall-Hugger, Wireless, HD Massage, Zero-Gravity, Memory Positions`,slug: ""},
			B06W2GYD8Y: {href: "https://amzn.to/3oC6Qef",nameProduct: `Real Relax 2020 Massage Chair, Full Body Zero Gravity Shiatsu Recliner with Bluetooth and Led Light, Black`,slug: ""},
			B00QRJALYI: {href: "https://amzn.to/2L8eYWg",nameProduct: `Delta Faucet Leland Single-Handle Touch Kitchen Sink Faucet with Pull Down Sprayer, Touch2O and ShieldSpray Technology, Magnetic Docking Spray Head, Arctic Stainless 9178T-AR-DST`,slug: ""},
			B001LZRF9M: {href: "https://amzn.to/39B55Kf",nameProduct: `EcoSmart ECO 11 Electric Tankless Water Heater, 13KW at 240 Volts with Patented Self Modulating Technology`,slug: ""},
			B01N80F68E: {href: "https://amzn.to/3r7B2j2",nameProduct: `Westinghouse WGen7500 Portable Generator with Remote Electric Start 7500 Rated Watts & 9500 Peak Watts, Gas Powered, CARB Compliant, Transfer Switch Ready`,slug: ""},
			B07JYXZ6VJ: {href: "https://amzn.to/3r9TlUU",nameProduct: `VIVOHOME 110V Electric Fireplace Insert Log Quartz Realistic Ember Bed Fan Heater with Infrared Remote Controller Black`,slug: ""},
			B074F8TZNH: {href: "https://amzn.to/3pDrzje",nameProduct: `Brother SE600 Sewing and Embroidery Machine, 80 Designs, 103 Built-In Stitches, Computerized, 4" x 4" Hoop Area, 3.2" LCD Touchscreen Display, 7 Included Feet`,slug: ""},
			B00UHNM1R0: {href: "https://amzn.to/3amWzh2",nameProduct: `BOSTITCH Pancake Air Compressor, Oil-Free, 6 Gallon, 150 PSI (BTFP02012)`,slug: ""},
			B006UKLUFS: {href: "https://amzn.to/36vXSsS",nameProduct: `Cuisinart ICE-100 Compressor Ice Cream and Gelato Maker, Silver, 1-1/2-Quart`,slug: ""},
			B089YSKJY6: {href: "https://amzn.to/36wOKV5",nameProduct: `COMFEE’ 1.6 Cu.ft Portable Washing Machine, 11lbs Capacity Fully Automatic Compact Washer with Wheels, 6 Wash Programs Laundry Washer with Drain Pump, Ideal for Apartments, RV, Camping, Magnetic Gray`,slug: ""},
			B005Q3VXDY: {href: "https://amzn.to/2O0s2yh",nameProduct: `simplehuman Kitchen Steel Frame Dish Rack With Swivel Spout, Fingerprint-Proof Stainless Steel Frame, Grey Plastic`,slug: ""},
			B07CPW4BXH: {href: "https://amzn.to/3rffLEu",nameProduct: `Sweetnight King Mattress in a Box - 12 Inch Plush Pillow Top Hybrid Mattress, Gel Memory Foam for Sleep Cool, Motion Isolating Individually Wrapped Coils, King Size, Twilight`,slug: ""},
			B07GGF5RFF: {href: "https://amzn.to/3oA2Tqt",nameProduct: `Zinus Josh Traditional Upholstered 77.5 Inch Sofa/Living Room Couch, Beige Weave`,slug: ""},
			B01DD6C4TC: {href: "https://amzn.to/36vG15e",nameProduct: `Mr. Heater F274830 MH18BRV Big Buddy Grey Indoor-Safe Portable RV Propane Heater (4,000 , 9,000 and 18,000 BTU)`,slug: ""},
			B00EUKHACW: {href: "https://amzn.to/3j9ekV8",nameProduct: `Shark Rocket Ultra-Light Corded Bagless Vacuum for Carpet and Hard Floor Cleaning with Swivel Steering and Car Detail Set (HV302), Gray/Orange`,slug: ""},
			B07T2G5Q6B: {href: "https://amzn.to/39C1dsk",nameProduct: `simplehuman, Black Stainless Steel 58 Liter / 15.3 Gallon Rectangular Voice and Motion Sensor Automatic Kitchen Trash Can`,slug: ""},
			B016WJWC0S: {href: "https://amzn.to/3amb4BT",nameProduct: `Olee Sleep 10 Inch Gel Infused Layer Top Memory Foam Mattress Blue, Queen`,slug: ""},
			B07FPHDC32: {href: "https://amzn.to/3pDsZdy",nameProduct: `Human Touch NOVO XT2 Massage Chair, One Size, Red`,slug: ""},
			B00H2RSA88: {href: "https://amzn.to/3r7CwK8",nameProduct: `Sleep Innovations Marley 10-inch Cooling Gel Memory Foam Mattress Bed in a Box, Made in the USA, King, White`,slug: ""},
			B00JH98GR4: {href: "https://amzn.to/2L8gSpS",nameProduct: `Shark Navigator Lift-Away Deluxe NV360 Upright Vacuum, Blue`,slug: ""},
			B002G51BZU: {href: "https://amzn.to/2MNsKhn",nameProduct: `Mr. Heater F232000 MH9BX Buddy 4,000-9,000-BTU Indoor-Safe Portable Propane Radiant Heater, Red-Black`,slug: ""},
			B01EAG9XLG: {href: "https://amzn.to/36zqRMp",nameProduct: `Sleep Innovations Shea 10-inch Memory Foam Mattress, Bed in a Box, Made in the USA, 10-Year Warranty - Queen Size`,slug: ""},
			B01ET84Y46: {href: "https://amzn.to/2Yxd98B",nameProduct: `Modway Aveline 8" Gel Infused Memory Foam Full Mattress With CertiPUR-US Certified Foam`,slug: ""},
			B07CN38M23: {href: "https://amzn.to/2MPihCs",nameProduct: `Masterbuilt MB20071117 Digital Electric Smoker`,slug: ""},
			B07D2V7TMY: {href: "https://amzn.to/3cxrUjG",nameProduct: `PORTABLE DIGITAL ICE MAKER MACHINE by Arctic-Pro with Ice Scoop, First Ice in 6-8 Minutes, 26 Pounds Daily, Great for Kitchens, Tailgating, Bars, Party, Small/Large Cubes, Silver, 11.5x8.7x12.5 Inch`,slug: ""},
			B07CWLRXBK: {href: "https://amzn.to/3asGLJN",nameProduct: `HOFISH 10 Inch Medium Firm Gel-Infused Memory Foam Mattress - Ideal Support & Great Motion Isolation - CertiPUR-US Certified Foam - Medium Firm - Queen`,slug: ""},
			B07FP186CN: {href: "https://amzn.to/2LcBA8c",nameProduct: `TOTO MS900CUMFG#01 Neorest NX1 Electronic Dual Flush Toilet - Cotton White`,slug: ""},
			B0734CXX69: {href: "https://amzn.to/2NYclYj",nameProduct: `Zinus Dachelle Upholstered Button Tufted Premium Platform Bed / Mattress Foundation / Easy Assembly / Strong Wood Slat Support / Dark Grey, Full`,slug: ""},
			B00WNNYSJG: {href: "https://amzn.to/36wQUEb",nameProduct: `UltraHD Tall Storage Cabinet - Stainless Steel`,slug: ""},
			B006MIUM20: {href: "https://amzn.to/2NXIsaw",nameProduct: `Zinus Shawn 14 Inch SmartBase Mattress Foundation / Platform Bed Frame / Box Spring Replacement / Quiet Noise-Free / Maximum Under-bed Storage, Queen`,slug: ""},
			B00CTTMDSC: {href: "https://amzn.to/2Moj0dP",nameProduct: `Steelcase Amia Ergonomic Office Chair with Adjustable Back Tension and Arms | Flexible Lumbar with Sliding Seat | Black Frame and Buzz2 Pumpkin Fabric`,slug: ""},
			B07DWZK22R: {href: "https://amzn.to/3cxudUc",nameProduct: `phiestina 46 Bottle Wine Cooler 24 Inch Dual Zone Built-in or Freestanding Wine Refrigerator with Compressor Cooling System`,slug: ""},
			B00BRUNPXQ: {href: "https://amzn.to/36yQkWf",nameProduct: `Sauder August Hill L-Shaped Desk, Dover Oak finish`,slug: ""},
			B01EAG9X84: {href: "https://amzn.to/2MoDDXi",nameProduct: `Sleep Innovations Shiloh 12-inch Memory Foam Mattress, Bed in a Box, Quilted Cover, Made in The USA, 10-Year Warranty - Queen Size`,slug: ""},
			B010E9ILY8: {href: "https://amzn.to/2YxdXdD",nameProduct: `Sauder Edge Water Computer Desk, Auburn Cherry finish`,slug: ""},
			B07F3DP48S: {href: "https://amzn.to/2NOSPgC",nameProduct: `Intex 26333EH Ultra XTR Set Above Ground Pool, 20ft X 48in, Gray`,slug: ""},
			B07L7GGMH8: {href: "https://amzn.to/3cASuZk",nameProduct: `LUNA Adult Weighted Blanket | 15 lbs - 60x80 - Queen Size Bed | 100% Oeko-Tex Certified Cooling Cotton & Premium Glass Beads | Designed in USA | Heavy Cool Weight for Hot & Cold Sleepers | Navy`,slug: ""},
			B004MXKUCY: {href: "https://amzn.to/3akttyU",nameProduct: `Simpson Cleaning MSH3125 MegaShot Gas Pressure Washer Powered by Honda GC190, 3200 PSI at 2.5 GPM`,slug: ""},
			B079W93GGX: {href: "https://amzn.to/3rcYk7h",nameProduct: `Nespresso by De'Longhi EN500W Lattissima One Original Espresso Machine with Milk Frotherby De'Longhi, Silky White`,slug: ""},
			B00D4NPMJE: {href: "https://amzn.to/3pHIxNk",nameProduct: `Fuji 2202 Semi-PRO 2 HVLP Spray System, Blue`,slug: ""},
			B00BWYO53G: {href: "https://amzn.to/3cDVi8h",nameProduct: `Honeywell HPA300 True HEPA Air Purifier, Extra-Large Room, Black`,slug: ""},
			B089QNP5KC: {href: "https://amzn.to/3oFElMP",nameProduct: `SYMA X500 4K Drone with UHD Camera for Adults, Easy GPS Quadcopter for Beginner with 56mins Flight Time, Brush Motor, 5GHz FPV Transmission, Auto Return Home, Follow Me, Light Positioning, 2 Batteries`,slug: ""},
			B07SY2Z5Y7: {href: "https://amzn.to/2YBS9xy",nameProduct: `Pulsar 12,000W Dual Fuel Portable Generator with Electric Start and Switch & Go Technology, CARB Approved PG12000B`,slug: ""},
			B077HW9XM7: {href: "https://amzn.to/3pJIAs7",nameProduct: `Ecovacs DEEBOT N79S Robotic Vacuum Cleaner with Max Power Suction, Upto 110 Min Runtime, Hard Floors and Carpets, Works with Alexa, App Controls, Self-Charging, Quiet`,slug: ""},
			B01DV3A8CC: {href: "https://amzn.to/3aFdBaz",nameProduct: `Infinity IT-8500 X3 – Full Body Zero Gravity 3D Massage Chair – Featuring Air Compression, Decompression Stretch, Lumbar Heat, and Shiatsu Technique – Brown, Zero Gravity Chair, Massage Recliner Chair`,slug: ""},
			B07DTKXTXV: {href: "https://amzn.to/3re9dWx",nameProduct: `Hoover Smartwash Automatic Carpet Cleaner, FH52000, Turquoise`,slug: ""},
			B00272N3DK: {href: "https://amzn.to/3pJM8uk",nameProduct: `Alera Valencia Series 60 by 30 by 29-1/2-Inch Desk Shell, Mahogany`,slug: ""},
			B009X43F38: {href: "https://amzn.to/3oB110F",nameProduct: `Hobart 500559 Handler 140 MIG Welder 115V`,slug: ""},
			B005A4ON90: {href: "https://amzn.to/3anDXxv",nameProduct: `Signature Sleep Memoir 8-Inch Memory Foam Mattress, Queen Size`,slug: ""},
			B012J1TFTE: {href: "https://amzn.to/3tkcmpG",nameProduct: `Olee Sleep 13 inch Galaxy Hybrid Gel Infused Memory Foam and Pocket Spring Mattress (Queen)`,slug: ""},
			B07PWQF712: {href: "https://amzn.to/2LeFgX4",nameProduct: `Colzer Portable Electronic Ice Maker Machine, Countertop Ice Maker,Make 9 Ice Cubes within 6-13 Minutes,33lbs Ice in 24 hours,Water Tank and Ice Scoop, Home,Kitchen,Bar,KTV (silver)`,slug: ""},
			B01M0N8256: {href: "https://amzn.to/36BQ7Sq",nameProduct: `DuroMax XP12000EH Dual Fuel Portable Generator - 12000 Watt Gas or Propane Powered-Electric Start- Home Back Up & RV Ready, 50 State Approved,Blue and Black`,slug: ""},
			B01NAUZJPE: {href: "https://amzn.to/2NYEUEY",nameProduct: `Rheem 240V Heating Chamber RTEX-13 Residential Tankless Water Heater`,slug: ""},
			B079L5D89G: {href: "https://amzn.to/3amLgWk",nameProduct: `Ficmax Ergonomic Gaming Chair Massage Computer Gaming Chair Reclining Racing Office Chair with Footrest High Back Gamer Chair for E-sports Large size Gaming Desk Chair with Headrest and Lumbar Support`,slug: ""},
			B01BMCWJ7G: {href: "https://amzn.to/2MMKN7o",nameProduct: `BedJet 3 Climate Comfort for Beds, Cooling Fan + Heating Air (Single Temp. Zone Any Size Bed or Mattress)`,slug: ""},
			B07GYZS4RJ: {href: "https://amzn.to/3rhkcye",nameProduct: `Stiebel Eltron Tankless Water Heater – Tempra 24 Plus – Electric, On Demand Hot Water, Eco, White, 20.2`,slug: ""},
			B07S864GPW: {href: "https://amzn.to/3ti0dBo",nameProduct: `Shark IQ Robot Self-Empty XL RV1001AE, Robotic Vacuum, IQ Navigation, Home Mapping, Self-Cleaning Brushroll, Wi-Fi Connected, Works with Alexa`,slug: ""},
			B007HIKQCK: {href: "https://amzn.to/3tjjQt6",nameProduct: `Bio Bidet BB-600 BioBidet BB600 Ultimate Advanced Bidet Toilet Seat, White, Elongated`,slug: ""},
			B008EYOPPU: {href: "https://amzn.to/2MJqJTJ",nameProduct: `Cuisinart GR-150P1 GR-150 Griddler Deluxe, Brushed Stainless`,slug: ""},
			B0799Q45TT: {href: "https://amzn.to/2LeFyNE",nameProduct: `Black + Decker BPWM09W Portable Washer`,slug: ""},
			B06XNQ8QDW: {href: "https://amzn.to/3jb5hmM",nameProduct: `STANLEY SLP2050 Electric Power Washer, Medium, Yellow`,slug: ""},
			B07GJR5M6L: {href: "https://amzn.to/3cxteDt",nameProduct: `ENKEEO Power Station 155 Wh Portable Charger Lithium Backup Battery Pack 110V 100W Solar Generator (Solar Panel Optional) AC Outlet USB DC Supply for Outdoors Camping Travel Fishing Hunting Emergency`,slug: ""},
			B07MMMYTV7: {href: "https://amzn.to/3oNS3xv",nameProduct: `VETOMILE 200W Peak Solar Generator, 45000mAh Portable Power Station with Pure Sine Wave 110V AC Outlet 3 USB Ports, 2 DC Ports 150W Rated Power Supply Pack for CPAP Outdoor Camping Backup`,slug: ""},
			B07JCZKJYB: {href: "https://amzn.to/3tk0PGD",nameProduct: `COLZER 232 PPD Commercial Dehumidifier, Large Industrial Dehumidifier with Hose for Basements, Warehouse & Job Sites Clean-Up, Flood, Water Damage Restoration - Moisture Removal Up to 29 Gallons/Day`,slug: ""},
			B00HHO0IEU: {href: "https://amzn.to/2Lgv2pa",nameProduct: `Intex 77in PureSpa Portable Bubble Massage Spa Set`,slug: ""},
			B08B8YQB99: {href: "https://amzn.to/36wFYpO",nameProduct: `Intex 28431E PureSpa Plus 85in x 25in Outdoor Portable Inflatable 6 Person Round Hot Tub Spa with 170 Bubble Jets, Built in Heater Pump, and 6 Type S1 Filter Replacement Cartridges`,slug: ""},
			B00NB3P98G: {href: "https://amzn.to/3r7udy2",nameProduct: `Coleman SaluSpa Inflatable Hot Tub Spa, Green & White`,slug: ""},
			B015W8E3J8: {href: "https://amzn.to/3tluj70",nameProduct: `Intex 77in PureSpa Portable Bubble Massage Spa Set`,slug: ""},
			B082324K53: {href: "https://amzn.to/3apQvEz",nameProduct: `Intex 28431E PureSpa Plus 85in x 25in Outdoor Portable Inflatable 6 Person Round Hot Tub Spa with 170 Bubble Jets, Cover, LED Light, and Built in Heater Pump, Navy`,slug: ""},
			B003R28HWQ: {href: "https://amzn.to/3pHNhma",nameProduct: `Breville JE98XL Juice Fountain Plus Centrifugal Juicer, Brushed Stainless Steel`,slug: ""},
			B0044BBOQK: {href: "https://amzn.to/3j7uYo9",nameProduct: `Kreg K4MS Jig Master System (K4MS)`,slug: ""},
			B00FAW4O0A: {href: "https://amzn.to/3oJPbBn",nameProduct: `SoundAsleep Dream Series Air Mattress with ComfortCoil Technology & Internal High Capacity Pump - Queen Size`,slug: ""},
			B00Q7EPSHI: {href: "https://amzn.to/2L9hxHB",nameProduct: `Zinus Green Tea Memory Foam Mattress, Queen, White`,slug: ""},
			B01AWXC70U: {href: "https://amzn.to/2YBUhFy",nameProduct: `Intex 28409E PureSpa 6 Person Home Outdoor Inflatable Portable Heated Round Hot Tub Spa 85-inch x 28-inch with 170 Bubble Jets and Built in Heat Pump, Blue`,slug: ""},
			B01MSZ036Q: {href: "https://amzn.to/3oG9M9G",nameProduct: `Dyson V7 Motorhead Cordless Stick Vacuum Cleaner, Fuchsia (227591-01)`,slug: ""},
			B012YMY3ZE: {href: "https://amzn.to/3j7nq4G",nameProduct: `Bestway Paris AirJet Hot Tub, (6-Person)`,slug: ""},
			B073FKF9KN: {href: "https://amzn.to/2YCk2p6",nameProduct: `Intex 15ft X 48in Easy Set Pool Set with Filter Pump, Ladder, Ground Cloth & Pool Cover`,slug: ""},
			B00PCGHJPQ: {href: "https://amzn.to/36BPQyC",nameProduct: `Skywalker Trampolines 15 Foot Jump N Dunk Round Trampoline with Enclosure-Basketball`,slug: ""},
			B01IY813UU: {href: "https://amzn.to/3tiP6Z7",nameProduct: `Snapper XD 82V MAX Electric Cordless 21" Push Lawn Mower, Battery and Charger Not Included`,slug: ""},
			B00HVF3JGO: {href: "https://amzn.to/3oEtOlb",nameProduct: `A-iPower SUA12000E 12,000-Watt Gasoline Powered Generator with Electric Start, 12000 Watt, Red/Black`,slug: ""},
			B00DCCYD6U: {href: "https://amzn.to/2YCGnmk",nameProduct: `iRobot Braava 380t Advanced Robot Mop- Wet Mopping and Dry Sweeping Cleaning Modes, Large Spaces`,slug: ""},
			B07G3ZNK4Y: {href: "https://amzn.to/2MrAyFN",nameProduct: `Vector Robot by Anki, A Home Robot Who Hangs Out & Helps Out, With Amazon Alexa Built-In`,slug: ""},
			B07H7L92QD: {href: "https://amzn.to/3j9N5tp",nameProduct: `PAXCESS Electric Pressure Washer 2150 PSI 1.85 GPM High Pressure Power Washer Machine with All-in-One Nozzle, Hose Reel, Detergent Tank Best for Cleaning Homes/Buildings/Cars, Decks, Driveways, Patios`,slug: ""},
			B00UHNM1R0: {href: "https://amzn.to/3j8MiZS",nameProduct: `BOSTITCH Pancake Air Compressor, Oil-Free, 6 Gallon, 150 PSI (BTFP02012)`,slug: ""},
			B06XFVQFP9: {href: "https://amzn.to/3j7Fyva",nameProduct: `LG LW6017R 6,000 BTU 115V Window Air Conditioner`,slug: ""},
			B0026SR0FW: {href: "https://amzn.to/3oGat2M",nameProduct: `Graco Magnum 262800 X5 Stand Airless Paint Sprayer, Blue`,slug: ""},
			B01C9RIACG: {href: "https://amzn.to/3cwSh9v",nameProduct: `Coway Airmega 400 Smart Air Purifier with 1,560 sq. ft. Coverage`,slug: ""},
			B00HQONFY6: {href: "https://amzn.to/3reyqQu",nameProduct: `WEN 4214 12-Inch Variable Speed Drill Press,Orange`,slug: ""},
			B072PZ4LVN: {href: "https://amzn.to/2MJ5Urw",nameProduct: `Amazon Brand – Rivet Revolve Modern Upholstered Sofa Couch, 80"W, Grey Weave`,slug: ""},
			B01923E15A: {href: "https://amzn.to/3jdoXpR",nameProduct: `Avallon ABR241SGRH 140 Can 24" Built-In Beverage Cooler - Right Hinge`,slug: ""},
			B07GL7PNPQ: {href: "https://amzn.to/3pBPiAm",nameProduct: `Traeger Grills TFB88PZBO Pro Series 34 Pellet Grill and Smoker, 884 Sq. In. Cooking Capacity, Bronze`,slug: ""},
			B01D8DAYBA: {href: "https://amzn.to/2MjQQAO",nameProduct: `Winix 5300-2 Air Purifier with True HEPA, PlasmaWave and Odor Reducing Carbon Filter,Gray`,slug: ""},
			B0792BWMV4: {href: "https://amzn.to/39CE09m",nameProduct: `Roborock Robot Vacuum and Mop with Adaptive Routing,Multi-Floor Mapping, Selective Room Cleaning, Super Strong Suction, Robotic Vacuum Cleaner Works with Alexa`,slug: ""},
			B01DE8PN10: {href: "https://amzn.to/39CCTqe",nameProduct: `Leggett & Platt Prodigy 2.0 Adjustable Bed with 10" Gel Cool Mattresses (split king(2 twin xl matts))`,slug: ""},
			B07GXZ49DY: {href: "https://amzn.to/3j8MTuA",nameProduct: `Kahuna Massage Chair LM-6800 Black`,slug: ""},
			B07FFMTW8X: {href: "https://amzn.to/3cvjcm3",nameProduct: `Tineco A11 Hero Cordless Lightweight Stick/Handheld Vacuum Cleaner, 450W Motor for Ultra Powerful Suction for Carpet, Hard Floor & Pet`,slug: ""},
			B00LIAP2ZY: {href: "https://amzn.to/2Mh0OCZ",nameProduct: `LG WM3997HWA Ventless 4.3 Cu. Ft. Capacity Steam Washer/Dryer Combination with TurboWash, TrueBalance Anti-Vibration System, NeveRust Stainless Steel Drum, Allergiene Cycle in White`,slug: ""},
			B01DLPUWL2: {href: "https://amzn.to/3awcJVE",nameProduct: `Black + Decker BPACT08WT Portable Air Conditioner, 8,000 BTU`,slug: ""},
			B01N1I9D6E: {href: "https://amzn.to/2LgxCLS",nameProduct: `WoodBridge T-0001 One Piece Toilet, Rectangle Button and Soft Closing Seat - Dual Flush, Elongated, Comfort Height, Water Sense, High-Efficiency`,slug: ""},
			B07RGM11L5: {href: "https://amzn.to/2MJtJzt",nameProduct: `Frigidaire 5,000 BTU 115V Window-Mounted Mini-Compact Air Conditioner with Mechanical Controls, White`,slug: ""},
			B0128T2HQK: {href: "https://amzn.to/3aonlFY",nameProduct: `SmartBidet SB-1000 Electric Bidet Seat for Elongated Toilets with Remote Control- Electronic Heated Toilet Seat with Warm Air Dryer and Temperature Controlled Wash Functions (White)`,slug: ""},
			B08D3HW1MQ: {href: "https://amzn.to/2MJtDrB",nameProduct: `ECOTRIC Electric Powerful Bicycle 26“ Fat Tire Bike 500W 36V/12AH Battery EBike Moped Snow Beach Mountain Ebike Throttle & Pedal Assist`,slug: ""},
			B07J31T4NC: {href: "https://amzn.to/3j7GvDK",nameProduct: `Nod by Tuft & Needle, Adaptive Foam 8-Inch Mattress, Queen`,slug: ""},
			B06W54K29J: {href: "https://amzn.to/2Mij4vP",nameProduct: `LEVOIT Air Purifier for Home Large Room,Smoke and Odor Eliminator, H13 True HEPA Filter for Bedroom, Auto Mode & 12h Timer, Cleaners for Allergies and Pets, Mold Pollen Dust, LV-PUR131, White`,slug: ""},
			B076MK5MHY: {href: "https://amzn.to/3pHxVhx",nameProduct: `Seatcraft Anthem Home Theater Seating Leather Multimedia Power Recline Sofa with Fold-Down Table, Adjustable Powered Headrests, Storage, AC/USB and Wireless Charging and Cup Holders (Black)`,slug: ""},
			B07GNSHPBQ: {href: "https://amzn.to/2YFIQwc",nameProduct: `Dash DFAF455GBAQ01 Deluxe Electric Air Fryer + Oven Cooker with Temperature Control, Non-stick Fry Basket, Recipe Guide + Auto Shut Off Feature, 1700-Watt, 6 Quart, 6 qt, Aqua`,slug: ""},
			B00FLYWNYQ: {href: "https://amzn.to/3rei3n5",nameProduct: `Instant Pot Duo 7-in-1 Electric Pressure Cooker, Sterilizer, Slow Cooker, Rice Cooker, Steamer, Saute, Yogurt Maker, and Warmer, 6 Quart, 14 One-Touch Programs`,slug: ""},
			B077VRX8TV: {href: "https://amzn.to/3tsUxVj",nameProduct: `Dash DMW001CU Machine for Individual, Paninis, Hash Browns, & other Mini waffle maker, 4 inch, Copper`,slug: ""},
			B077HW9XM7: {href: "https://amzn.to/39Y2JVX",nameProduct: `Ecovacs n79s robot vacuum, Dark Brown`,slug: ""},
			B07GB3FNNV: {href: "https://amzn.to/3aVRj46",nameProduct: `Instant Pot Aura Multi-Use Programmable Slow Cooker, 6 Quart, No Pressure Cooking Functionality`,slug: ""},
			B07F2D81JN: {href: "https://amzn.to/2ZaoA69",nameProduct: `Amarey A800 Robot Vacuum - Super Suction Robotic Vacuum Cleaner, Long Lasting, Timer Function, Self-Charging, Multiple Cleaning Modes, Amarey Robot Vacuum Cleaner for Pet Hair, Hard Floor, Carpet`,slug: ""},
			B01CS3J570: {href: "https://amzn.to/37zKapA",nameProduct: `Honeywell HL10CESWK, 10, 000 BTU, Black/White Portable Air Conditioner, 10,000`,slug: ""},
			B00JJ5I7GQ: {href: "https://amzn.to/3ufw5ao",nameProduct: `Polaris F9550 Sport Robotic In-Ground Pool Cleaner`,slug: ""},
			B08NT4YBQ3: {href: "https://amzn.to/2NmbIrm",nameProduct: `Essential Hot Tubs 67-Jets 2021 Syracuse Hot Tub, Seats 5-6, Espresso`,slug: ""},
			B003IBGL7O: {href: "https://amzn.to/3aAPBGw",nameProduct: `Hayward HP21404T HeatPro In Ground 140,000 BTU Heat Pump`,slug: ""},
			B071VLNVMD: {href: "https://amzn.to/3pwk3WE",nameProduct: `Tempur-PedicTEMPUR-CloudLuxe Breeze 13.5-Inch Extra-Soft Cooling Foam Mattress, Queen, Made in USA, 10 Year Warranty`,slug: ""},
			B003145K3E: {href: "https://amzn.to/3dtfmKH",nameProduct: `Silverback 60" In-Ground Basketball Hoop, Adjustable Height Tempered Glass Backboard and Pro-style flex Rim`,slug: ""},
			B01D3FOIR4: {href: "https://amzn.to/2NgcFlj",nameProduct: `LG LW1216ER Window-Mounted Remote Control, 12,000 BTU 115V Air Conditioner, White`,slug: ""},
			B00QXIJSQU: {href: "https://amzn.to/3azWgAK",nameProduct: `Koldfront WAC8001W 8,000 BTU Window Air Conditioner with 3,500 BTU Heater and Remote`,slug: ""},
			B003CT55YW: {href: "https://amzn.to/3k9Px3U",nameProduct: `RabbitAir MinusA2 Ultra Quiet HEPA Air Purifier - Stylish, Efficient and Energy Star (SPA-700A, White, Odor Remover)`,slug: ""},
			B07D826M1Y: {href: "https://amzn.to/3k9Psx8",nameProduct: `LG LW1817IVSM 18,000 BTU Dual Inverter Window Air Conditioner, 230V, Remote Control, White`,slug: ""}
		}
	}
	return dataAMZ;
}
