function getData(){
	var dataAMZ = {
		B01MCUXJX1: {href: "https://amzn.to/2MM0fAS",slug: ""},
		B00Q7EPSHI: {href: "https://amzn.to/3rgjgKG",slug: ""},
		B00474X5DO: {href: "https://amzn.to/3cBu2qM",slug: ""},
		B003OBUE5I: {href: "https://amzn.to/2O26GR0",slug: ""},
		B00UCIOWRM: {href: "https://amzn.to/3ayORQS",slug: ""},
		B07S864GPW: {href: "https://amzn.to/3cDcjiE",slug: ""},
		B002WKJ5ES: {href: "https://amzn.to/3pPeiEo",slug: ""},
		B074QWYM22: {href: "https://amzn.to/3riwhmV",slug: ""},
		B008UHXUSO: {href: "https://amzn.to/36z43fV",slug: ""},
		B003145K3E: {href: "https://amzn.to/39Hr5D6",slug: ""},
		B071HNQSCM: {href: "https://amzn.to/36C1Zng",slug: ""},
		B003IBGL7O: {href: "https://amzn.to/39FMw7I",slug: ""},
		B08NT4YBQ3: {href: "https://amzn.to/3riwOoV",slug: ""},
		B00JJ5I7GQ: {href: "https://amzn.to/3oKXwVq",slug: ""},
		B06W54K29J: {href: "https://amzn.to/2MV4sT2",slug: ""},
		B07J31T4NC: {href: "https://amzn.to/3pOuIgf",slug: ""},
		B08D3HW1MQ: {href: "https://amzn.to/3rfYhYo",slug: ""},
		B0128T2HQK: {href: "https://amzn.to/3cDZgOa",slug: ""},
		B07RSM91SY: {href: "https://amzn.to/2MubUVb",slug: ""},
		B01DLPUWL2: {href: "https://amzn.to/39HNIHC",slug: ""},
		B07F3FTJCM: {href: "https://amzn.to/2O4Ucbh",slug: ""},
		B07GXZ49DY: {href: "https://amzn.to/3tp0fHF",slug: ""},
		B01DE8PN10: {href: "https://amzn.to/36Dpa0K",slug: ""},
		B077HW9XM7: {href: "https://amzn.to/3topmuw",slug: ""},
		B07GNSHPBQ: {href: "https://amzn.to/3rdGSiU",slug: ""},
		B019ZTXT0Y: {href: "https://amzn.to/3pMhErN",slug: ""},
		B0734CXX69: {href: "https://amzn.to/3tnfW2d",slug: ""},
		B00WNNYSJG: {href: "https://amzn.to/36HemOV",slug: ""},
		B00CTTMDSC: {href: "https://amzn.to/2MuWIHe",slug: ""},
		B07DWZK22R: {href: "https://amzn.to/39LuX6n",slug: ""},
		B07L7GGMH8: {href: "https://amzn.to/36GIutJ",slug: ""},
		B01EAG9X84: {href: "https://amzn.to/3roaiLg",slug: ""},
		B010E9ILY8: {href: "https://amzn.to/3avzysl",slug: ""},
		B07T2G5Q6B: {href: "https://amzn.to/36FgVkO",slug: ""},
		B016WJWC0S: {href: "https://amzn.to/3jhse7J",slug: ""},
		B00H2RSA88: {href: "https://amzn.to/3ay82dD",slug: ""},
		B00JH98GR4: {href: "https://amzn.to/2Lg0yDx",slug: ""},
		B01KZHOW3I: {href: "https://amzn.to/3pZvGXj",slug: ""},
		B00Z4TSRFW: {href: "https://amzn.to/3awLl9R",slug: ""},
		B07B42DWWC: {href: "https://amzn.to/39Q7OzL",slug: ""},
		B01FWIEIRU: {href: "https://amzn.to/2YHvtMf",slug: ""}
	}
	return dataAMZ;
}
