function getData(){
	const keysw = "www.thebesttipsca.com";
	var keyAPI = (typeof keyhost != 'undefined') ? keyhost : document.location.host;
	var dataAMZ = {};
	if(keysw == keyAPI){
		dataAMZ = {
			B01MCUXJX1: {href: "https://amzn.to/2MM0fAS",nameProduct: `Champion 3500-Watt Dual Fuel RV Ready Portable Generator`,slug: ""},
			B00Q7EPSHI: {href: "https://amzn.to/3rgjgKG",nameProduct: `Zinus Memory Foam 12 Inch Green Tea Mattress, Queen`,slug: ""},
			B00474X5DO: {href: "https://amzn.to/3cBu2qM",nameProduct: `LUCID 10 Inch Gel Memory Foam Mattress - Medium Feel - CertiPUR-US Certified - 10-Year Warranty - Queen`,slug: ""},
			B003OBUE5I: {href: "https://amzn.to/2O26GR0",nameProduct: `Weber Summit S-670 LP Gas Grill, 7370001`,slug: ""},
			B00UCIOWRM: {href: "https://amzn.to/3ayORQS",nameProduct: `TOTO SW2034#01 C100 WASHLET Electronic Bidet Toilet Seat with PreMist, Elongated, Cotton White`,slug: ""},
			B07S864GPW: {href: "https://amzn.to/3cDcjiE",nameProduct: `Shark IQ R1001AE with Self-Empty Base, Wi-Fi Connected, Home Mapping, Works with Alexa, Ideal for Pet Hair, Carpets, Hard Floors Robot Vacuum, 30 Session Capacity`,slug: ""},
			B002WKJ5ES: {href: "https://amzn.to/3pPeiEo",nameProduct: `Hayward Goldline AQR15 AquaRite Electronic Salt Chlorination System for In-Ground Pools , 40,000-Gallon Cell`,slug: ""},
			B074QWYM22: {href: "https://amzn.to/3riwhmV",nameProduct: `LUCID L300 Bed Base 5 Minute Assembly Adjustable, Twin XL, Charcoal`,slug: ""},
			B008UHXUSO: {href: "https://amzn.to/36z43fV",nameProduct: `Honeywell 1540-2471 CFM Outdoor Portable Evaporative Cooler with Triple-Sided Honeycomb Cooling Pad, CO60PM, Gray`,slug: ""},
			B003145K3E: {href: "https://amzn.to/39Hr5D6",nameProduct: `Silverback 60" In-Ground Basketball Hoop with Adjustable-Height Tempered Glass Backboard and Pro-Style Breakaway Rim`,slug: ""},
			B071HNQSCM: {href: "https://amzn.to/36C1Zng",nameProduct: `Tempur-PedicTEMPUR-CloudLuxe Breeze 13.5-Inch Extra-Soft Cooling Foam Mattress, California King, Made in USA, 10 Year Warranty`,slug: ""},
			B003IBGL7O: {href: "https://amzn.to/39FMw7I",nameProduct: `Hayward HP21404T HeatPro Titanium 140,000 BTU Heat Pump, Square`,slug: ""},
			B08NT4YBQ3: {href: "https://amzn.to/3riwOoV",nameProduct: `Essential Hot Tubs 67-Jet Syracuse Hot Tub, Seats 5-6, Espresso`,slug: ""},
			B00JJ5I7GQ: {href: "https://amzn.to/3oKXwVq",nameProduct: `Polaris F9550 Sport Robotic In-Ground Pool Cleaner`,slug: ""},
			B06W54K29J: {href: "https://amzn.to/2MV4sT2",nameProduct: `LEVOIT Air Purifier for Home Large Room with True HEPA Filter, LV-PUR131`,slug: ""},
			B07J31T4NC: {href: "https://amzn.to/3pOuIgf",nameProduct: `Nod by Tuft & Needle, Adaptive Foam 8-Inch Mattress, Queen`,slug: ""},
			B08D3HW1MQ: {href: "https://amzn.to/3rfYhYo",nameProduct: `ECOTRIC Fat Tire Electric Bike Beach Snow Bicycle 26" 4.0 inch Fat Tire ebike 500W 36V/12AH Electric Mountain Bicycle with Shimano 7 Speeds Lithium Battery Black/Orange/Blue`,slug: ""},
			B0128T2HQK: {href: "https://amzn.to/3cDZgOa",nameProduct: `SmartBidet SB-1000 Electric Bidet Seat for Elongated Toilets with Remote Control- Electronic Heated Toilet Seat with Warm Air Dryer and Temperature Controlled Wash Functions (White)`,slug: ""},
			B07RSM91SY: {href: "https://amzn.to/2MubUVb",nameProduct: `WoodBridge T-0001, Dual Flush Elongated One Piece Toilet with Soft Closing Seat, Comfort Height, Water Sense, High-Efficiency, Rectangle Button`,slug: ""},
			B01DLPUWL2: {href: "https://amzn.to/39HNIHC",nameProduct: `BLACK+DECKER BPACT08WT Portable Air Conditioner, 8,000 BTU, White`,slug: ""},
			B07F3FTJCM: {href: "https://amzn.to/2O4Ucbh",nameProduct: `Intex 18ft X 52in Ultra XTR Pool Set with Sand Filter Pump, Ladder, Ground Cloth & Pool Cover`,slug: ""},
			B07GXZ49DY: {href: "https://amzn.to/3tp0fHF",nameProduct: `Kahuna Massage Chair LM-6800 + 2 Years Extended Warranty - Space-Saving Zero Gravity Full-Body Recliner with Yoga & Heating Therapy (Black)`,slug: ""},
			B01DE8PN10: {href: "https://amzn.to/36Dpa0K",nameProduct: `Leggett & Platt Prodigy 2.0 Adjustable Bed with 10" Gel Cool Mattresses (split king(2 twin xl matts))`,slug: ""},
			B077HW9XM7: {href: "https://amzn.to/3topmuw",nameProduct: `Ecovacs DEEBOT N79S Robotic Vacuum Cleaner with Max Power Suction, Upto 110 Min Runtime, Hard Floors and Carpets, Works with Alexa, App Controls, Self-Charging, Quiet`,slug: ""},
			B07GNSHPBQ: {href: "https://amzn.to/3rdGSiU",nameProduct: `Dash DFAF455GBAQ01 Deluxe Electric Air Fryer + Oven Cooker with Temperature Control, Non-stick Fry Basket, Recipe Guide + Auto Shut Off Feature, 1700-Watt, 6 Quart, 6 qt, Aqua`,slug: ""},
			B019ZTXT0Y: {href: "https://amzn.to/3pMhErN",nameProduct: `Sunny Health & Fitness SF-T4400 Treadmill`,slug: ""},
			B0734CXX69: {href: "https://amzn.to/3tnfW2d",nameProduct: `Zinus Dachelle Upholstered Button Tufted Premium Platform Bed / Mattress Foundation / Easy Assembly / Strong Wood Slat Support / Dark Grey, Full`,slug: ""},
			B00WNNYSJG: {href: "https://amzn.to/36HemOV",nameProduct: `UltraHD Tall Storage Cabinet - Stainless Steel`,slug: ""},
			B00CTTMDSC: {href: "https://amzn.to/2MuWIHe",nameProduct: `Steelcase Amia Ergonomic Office Chair with Adjustable Back Tension and Arms | Flexible Lumbar with Sliding Seat | Black Frame and Buzz2 Pumpkin Fabric`,slug: ""},
			B07DWZK22R: {href: "https://amzn.to/39LuX6n",nameProduct: `Phiestina 46 Bottle Wine Cooler 24 Inch Dual Zone Built-in or Freestanding Wine Refrigerator with Compressor Cooling System`,slug: ""},
			B07L7GGMH8: {href: "https://amzn.to/36GIutJ",nameProduct: `LUNA Adult Weighted Blanket | 15 lbs - 60x80 - Queen Size Bed | 100% Oeko-Tex Certified Cooling Cotton & Premium Glass Beads | Designed in USA | Heavy Cool Weight for Hot & Cold Sleepers | Navy`,slug: ""},
			B01EAG9X84: {href: "https://amzn.to/3roaiLg",nameProduct: `Sleep Innovations Shiloh 12-inch Memory Foam Mattress, Bed in a Box, Quilted Cover, Made in The USA, 10-Year Warranty - Queen Size`,slug: ""},
			B010E9ILY8: {href: "https://amzn.to/3avzysl",nameProduct: `Sauder Edge Water Computer Desk, Auburn Cherry finish`,slug: ""},
			B07T2G5Q6B: {href: "https://amzn.to/36FgVkO",nameProduct: `simplehuman, Black Stainless Steel 58 Liter / 15.3 Gallon Rectangular Voice and Motion Sensor Automatic Kitchen Trash Can`,slug: ""},
			B016WJWC0S: {href: "https://amzn.to/3jhse7J",nameProduct: `Olee Sleep 10 Inch Gel Infused Layer Top Memory Foam Mattress Blue, Queen`,slug: ""},
			B00H2RSA88: {href: "https://amzn.to/3ay82dD",nameProduct: `Sleep Innovations Marley 10-inch Cooling Gel Memory Foam Mattress Bed in a Box, Made in the USA, King, White`,slug: ""},
			B00JH98GR4: {href: "https://amzn.to/2Lg0yDx",nameProduct: `Shark Navigator Lift-Away Deluxe NV360 Upright Vacuum, Blue`,slug: ""},
			B01KZHOW3I: {href: "https://amzn.to/3pZvGXj",nameProduct: `Bose Lifestyle 650 Black Home Entertainment System`,slug: ""},
			B00Z4TSRFW: {href: "https://amzn.to/3awLl9R",nameProduct: `Jura 15068 IMPRESSA C65 Automatic Coffee Machine, Platinum`,slug: ""},
			B07B42DWWC: {href: "https://amzn.to/39Q7OzL",nameProduct: `Nectar Queen Mattress + 2 Pillows Included - Gel Memory Foam Mattress - CertiPUR-US Certified Foams - 180 Night Home Trial - Forever Warranty`,slug: ""},
			B01FWIEIRU: {href: "https://amzn.to/2YHvtMf",nameProduct: `Sony Home Theater Projector VPL-HW45ES: 1080P Full HD Video Projector for TV, Movies and Gaming - Home Cinema Projector with 3 SXRD Imagers and 1,800 Lumens for Brightness - 3D Compatible`,slug: ""},
			B01LA3VHHU: {href: "https://amzn.to/3tuoEvK",nameProduct: `PuraFlame 33 Inches Western Electric Fireplace Insert with Remote Control, 750/1500W, Black`,slug: ""},
			B01ALBMIEI: {href: "https://amzn.to/2YN0Gxu",nameProduct: `Giantex Portable Mini Compact Twin Tub Washing Machine 17.6lbs Washer Spain Spinner Portable Washing Machine, Blue+ White`,slug: ""},
			B078MGY2CS: {href: "https://amzn.to/3ayzHvg",nameProduct: `Giantex Full-Automatic Washing Machine Portable Compact 1.6 Cu.ft Laundry Washer Spin with Drain Pump, 10 programs 8 Water Level Selections with LED Display 12 Lbs Capacity`,slug: ""},
			B071983575: {href: "https://amzn.to/3oPpm35",nameProduct: `Bush Furniture Cabot L Shaped Computer Desk in Harvest Cherry`,slug: ""},
			B07SG4KNT4: {href: "https://amzn.to/3twcpyS",nameProduct: `Cordless Vacuum, Deik Stick Vacuum Cleaner, 11 Kpa Powerful Suction 4 in 1 Lightweight Handheld Vacuum with Upgraded Motor and LED Brush for Pet Hair Home Hard Floor Carpet Car Cleaning`,slug: ""},
			B07MDZC6KG: {href: "https://amzn.to/39LpjRv",nameProduct: `ECOTOUCH Electric Tankless Water Heater Point-of-Use Hot Water Heater Digital Display for Energy Efficiency 5.5kW at 240V, White`,slug: ""},
			B07P7XDKMB: {href: "https://amzn.to/2O7UXAp",nameProduct: `Dreamfoam Bedding Chill 14" Gel Memory Foam Mattress, Full, Made in The USA`,slug: ""},
			B0752VPHVK: {href: "https://amzn.to/2LjDvHZ",nameProduct: `August Home August Smart Lock Pro + Connect with Wi-Fi Bridge, Dark Gray. Zwave, HomeKit & Alexa Compatible`,slug: ""},
			B00C03D01Q: {href: "https://amzn.to/39NyEIp",nameProduct: `Moen 900-001 Flo by Moen 3/4-Inch Smart Water Shutoff`,slug: ""},
			B075G61CVW: {href: "https://amzn.to/2N0iwKH",nameProduct: `Cangshan TS Series 1020885 Swedish Sandvik 14C28N Steel Forged 17-Piece Knife Block Set, Walnut`,slug: ""},
			B07L1P4SPB: {href: "https://amzn.to/2MBD24v",nameProduct: `Queen Mattress, Inofia 10 Inch Responsive Memory Foam Mattress, Hybrid Innerspring Mattress in a Box, Sleep Cooler with More Pressure Relief & Support, CertiPUR-US Certified, Double Size`,slug: ""}
		}
	}
	return dataAMZ;
}
