function getData(){
	const keysw = "www.thebesttipsca.com";
	var keyAPI = (typeof keyhost != 'undefined') ? keyhost : document.location.host;
	var dataAMZ = {};
	if(keysw == keyAPI){
		dataAMZ = {
			B01MCUXJX1: {href: "https://amzn.to/2MM0fAS",nameProduct: `Champion 3500-Watt Dual Fuel RV Ready Portable Generator`,slug: ""},
			B00Q7EPSHI: {href: "https://amzn.to/3rgjgKG",nameProduct: `Zinus Memory Foam 12 Inch Green Tea Mattress, Queen`,slug: ""},
			B00474X5DO: {href: "https://amzn.to/3cBu2qM",nameProduct: `LUCID 10 Inch Gel Memory Foam Mattress - Medium Feel - CertiPUR-US Certified - 10-Year Warranty - Queen`,slug: ""},
			B003OBUE5I: {href: "https://amzn.to/2O26GR0",nameProduct: `Weber Summit S-670 LP Gas Grill, 7370001`,slug: ""},
			B00UCIOWRM: {href: "https://amzn.to/3ayORQS",nameProduct: `TOTO SW2034#01 C100 WASHLET Electronic Bidet Toilet Seat with PreMist, Elongated, Cotton White`,slug: ""},
			B07S864GPW: {href: "https://amzn.to/3cDcjiE",nameProduct: `Shark IQ R1001AE with Self-Empty Base, Wi-Fi Connected, Home Mapping, Works with Alexa, Ideal for Pet Hair, Carpets, Hard Floors Robot Vacuum, 30 Session Capacity`,slug: ""},
			B002WKJ5ES: {href: "https://amzn.to/3pPeiEo",nameProduct: `Hayward Goldline AQR15 AquaRite Electronic Salt Chlorination System for In-Ground Pools , 40,000-Gallon Cell`,slug: ""},
			B074QWYM22: {href: "https://amzn.to/3riwhmV",nameProduct: `LUCID L300 Bed Base 5 Minute Assembly Adjustable, Twin XL, Charcoal`,slug: ""},
			B008UHXUSO: {href: "https://amzn.to/36z43fV",nameProduct: `Honeywell 1540-2471 CFM Outdoor Portable Evaporative Cooler with Triple-Sided Honeycomb Cooling Pad, CO60PM, Gray`,slug: ""},
			B003145K3E: {href: "https://amzn.to/39Hr5D6",nameProduct: `Silverback 60" In-Ground Basketball Hoop with Adjustable-Height Tempered Glass Backboard and Pro-Style Breakaway Rim`,slug: ""},
			B071HNQSCM: {href: "https://amzn.to/36C1Zng",nameProduct: `Tempur-PedicTEMPUR-CloudLuxe Breeze 13.5-Inch Extra-Soft Cooling Foam Mattress, California King, Made in USA, 10 Year Warranty`,slug: ""},
			B003IBGL7O: {href: "https://amzn.to/39FMw7I",nameProduct: `Hayward HP21404T HeatPro Titanium 140,000 BTU Heat Pump, Square`,slug: ""},
			B08NT4YBQ3: {href: "https://amzn.to/3riwOoV",nameProduct: `Essential Hot Tubs 67-Jet Syracuse Hot Tub, Seats 5-6, Espresso`,slug: ""},
			B00JJ5I7GQ: {href: "https://amzn.to/3oKXwVq",nameProduct: `Polaris F9550 Sport Robotic In-Ground Pool Cleaner`,slug: ""},
			B06W54K29J: {href: "https://amzn.to/2MV4sT2",nameProduct: `LEVOIT Air Purifier for Home Large Room with True HEPA Filter, LV-PUR131`,slug: ""},
			B07J31T4NC: {href: "https://amzn.to/3pOuIgf",nameProduct: `Nod by Tuft & Needle, Adaptive Foam 8-Inch Mattress, Queen`,slug: ""},
			B08D3HW1MQ: {href: "https://amzn.to/3rfYhYo",nameProduct: `ECOTRIC Fat Tire Electric Bike Beach Snow Bicycle 26" 4.0 inch Fat Tire ebike 500W 36V/12AH Electric Mountain Bicycle with Shimano 7 Speeds Lithium Battery Black/Orange/Blue`,slug: ""},
			B0128T2HQK: {href: "https://amzn.to/3cDZgOa",nameProduct: `SmartBidet SB-1000 Electric Bidet Seat for Elongated Toilets with Remote Control- Electronic Heated Toilet Seat with Warm Air Dryer and Temperature Controlled Wash Functions (White)`,slug: ""},
			B07RSM91SY: {href: "https://amzn.to/2MubUVb",nameProduct: `WoodBridge T-0001, Dual Flush Elongated One Piece Toilet with Soft Closing Seat, Comfort Height, Water Sense, High-Efficiency, Rectangle Button`,slug: ""},
			B01DLPUWL2: {href: "https://amzn.to/39HNIHC",nameProduct: `BLACK+DECKER BPACT08WT Portable Air Conditioner, 8,000 BTU, White`,slug: ""},
			B07F3FTJCM: {href: "https://amzn.to/2O4Ucbh",nameProduct: `Intex 18ft X 52in Ultra XTR Pool Set with Sand Filter Pump, Ladder, Ground Cloth & Pool Cover`,slug: ""},
			B07GXZ49DY: {href: "https://amzn.to/3tp0fHF",nameProduct: `Kahuna Massage Chair LM-6800 + 2 Years Extended Warranty - Space-Saving Zero Gravity Full-Body Recliner with Yoga & Heating Therapy (Black)`,slug: ""},
			B01DE8PN10: {href: "https://amzn.to/36Dpa0K",nameProduct: `Leggett & Platt Prodigy 2.0 Adjustable Bed with 10" Gel Cool Mattresses (split king(2 twin xl matts))`,slug: ""},
			B077HW9XM7: {href: "https://amzn.to/3topmuw",nameProduct: `Ecovacs DEEBOT N79S Robotic Vacuum Cleaner with Max Power Suction, Upto 110 Min Runtime, Hard Floors and Carpets, Works with Alexa, App Controls, Self-Charging, Quiet`,slug: ""},
			B07GNSHPBQ: {href: "https://amzn.to/3rdGSiU",nameProduct: `Dash DFAF455GBAQ01 Deluxe Electric Air Fryer + Oven Cooker with Temperature Control, Non-stick Fry Basket, Recipe Guide + Auto Shut Off Feature, 1700-Watt, 6 Quart, 6 qt, Aqua`,slug: ""},
			B019ZTXT0Y: {href: "https://amzn.to/3pMhErN",nameProduct: `Sunny Health & Fitness SF-T4400 Treadmill`,slug: ""},
			B0734CXX69: {href: "https://amzn.to/3tnfW2d",nameProduct: `Zinus Dachelle Upholstered Button Tufted Premium Platform Bed / Mattress Foundation / Easy Assembly / Strong Wood Slat Support / Dark Grey, Full`,slug: ""},
			B00WNNYSJG: {href: "https://amzn.to/36HemOV",nameProduct: `UltraHD Tall Storage Cabinet - Stainless Steel`,slug: ""},
			B00CTTMDSC: {href: "https://amzn.to/2MuWIHe",nameProduct: `Steelcase Amia Ergonomic Office Chair with Adjustable Back Tension and Arms | Flexible Lumbar with Sliding Seat | Black Frame and Buzz2 Pumpkin Fabric`,slug: ""},
			B07DWZK22R: {href: "https://amzn.to/39LuX6n",nameProduct: `Phiestina 46 Bottle Wine Cooler 24 Inch Dual Zone Built-in or Freestanding Wine Refrigerator with Compressor Cooling System`,slug: ""},
			B07L7GGMH8: {href: "https://amzn.to/36GIutJ",nameProduct: `LUNA Adult Weighted Blanket | 15 lbs - 60x80 - Queen Size Bed | 100% Oeko-Tex Certified Cooling Cotton & Premium Glass Beads | Designed in USA | Heavy Cool Weight for Hot & Cold Sleepers | Navy`,slug: ""},
			B01EAG9X84: {href: "https://amzn.to/3roaiLg",nameProduct: `Sleep Innovations Shiloh 12-inch Memory Foam Mattress, Bed in a Box, Quilted Cover, Made in The USA, 10-Year Warranty - Queen Size`,slug: ""},
			B010E9ILY8: {href: "https://amzn.to/3avzysl",nameProduct: `Sauder Edge Water Computer Desk, Auburn Cherry finish`,slug: ""},
			B07T2G5Q6B: {href: "https://amzn.to/36FgVkO",nameProduct: `simplehuman, Black Stainless Steel 58 Liter / 15.3 Gallon Rectangular Voice and Motion Sensor Automatic Kitchen Trash Can`,slug: ""},
			B016WJWC0S: {href: "https://amzn.to/3jhse7J",nameProduct: `Olee Sleep 10 Inch Gel Infused Layer Top Memory Foam Mattress Blue, Queen`,slug: ""},
			B00H2RSA88: {href: "https://amzn.to/3ay82dD",nameProduct: `Sleep Innovations Marley 10-inch Cooling Gel Memory Foam Mattress Bed in a Box, Made in the USA, King, White`,slug: ""},
			B00JH98GR4: {href: "https://amzn.to/2Lg0yDx",nameProduct: `Shark Navigator Lift-Away Deluxe NV360 Upright Vacuum, Blue`,slug: ""},
			B01KZHOW3I: {href: "https://amzn.to/3pZvGXj",nameProduct: `Bose Lifestyle 650 Black Home Entertainment System`,slug: ""},
			B00Z4TSRFW: {href: "https://amzn.to/3awLl9R",nameProduct: `Jura 15068 IMPRESSA C65 Automatic Coffee Machine, Platinum`,slug: ""},
			B07B42DWWC: {href: "https://amzn.to/39Q7OzL",nameProduct: `Nectar Queen Mattress + 2 Pillows Included - Gel Memory Foam Mattress - CertiPUR-US Certified Foams - 180 Night Home Trial - Forever Warranty`,slug: ""},
			B01FWIEIRU: {href: "https://amzn.to/2YHvtMf",nameProduct: `Sony Home Theater Projector VPL-HW45ES: 1080P Full HD Video Projector for TV, Movies and Gaming - Home Cinema Projector with 3 SXRD Imagers and 1,800 Lumens for Brightness - 3D Compatible`,slug: ""},
			B01LA3VHHU: {href: "https://amzn.to/3tuoEvK",nameProduct: `PuraFlame 33 Inches Western Electric Fireplace Insert with Remote Control, 750/1500W, Black`,slug: ""},
			B01ALBMIEI: {href: "https://amzn.to/2YN0Gxu",nameProduct: `Giantex Portable Mini Compact Twin Tub Washing Machine 17.6lbs Washer Spain Spinner Portable Washing Machine, Blue+ White`,slug: ""},
			B078MGY2CS: {href: "https://amzn.to/3ayzHvg",nameProduct: `Giantex Full-Automatic Washing Machine Portable Compact 1.6 Cu.ft Laundry Washer Spin with Drain Pump, 10 programs 8 Water Level Selections with LED Display 12 Lbs Capacity`,slug: ""},
			B071983575: {href: "https://amzn.to/3oPpm35",nameProduct: `Bush Furniture Cabot L Shaped Computer Desk in Harvest Cherry`,slug: ""},
			B07SG4KNT4: {href: "https://amzn.to/3twcpyS",nameProduct: `Cordless Vacuum, Deik Stick Vacuum Cleaner, 11 Kpa Powerful Suction 4 in 1 Lightweight Handheld Vacuum with Upgraded Motor and LED Brush for Pet Hair Home Hard Floor Carpet Car Cleaning`,slug: ""},
			B07MDZC6KG: {href: "https://amzn.to/39LpjRv",nameProduct: `ECOTOUCH Electric Tankless Water Heater Point-of-Use Hot Water Heater Digital Display for Energy Efficiency 5.5kW at 240V, White`,slug: ""},
			B07P7XDKMB: {href: "https://amzn.to/2O7UXAp",nameProduct: `Dreamfoam Bedding Chill 14" Gel Memory Foam Mattress, Full, Made in The USA`,slug: ""},
			B0752VPHVK: {href: "https://amzn.to/2LjDvHZ",nameProduct: `August Home August Smart Lock Pro + Connect with Wi-Fi Bridge, Dark Gray. Zwave, HomeKit & Alexa Compatible`,slug: ""},
			B00C03D01Q: {href: "https://amzn.to/39NyEIp",nameProduct: `Moen 900-001 Flo by Moen 3/4-Inch Smart Water Shutoff`,slug: ""},
			B075G61CVW: {href: "https://amzn.to/2N0iwKH",nameProduct: `Cangshan TS Series 1020885 Swedish Sandvik 14C28N Steel Forged 17-Piece Knife Block Set, Walnut`,slug: ""},
			B07L1P4SPB: {href: "https://amzn.to/2MBD24v",nameProduct: `Queen Mattress, Inofia 10 Inch Responsive Memory Foam Mattress, Hybrid Innerspring Mattress in a Box, Sleep Cooler with More Pressure Relief & Support, CertiPUR-US Certified, Double Size`,slug: ""},
			B01M3R711N: {href: "https://amzn.to/2MUhAb0",nameProduct: `Champion 4000-Watt RV Ready DH Series Open Frame Inverter with Quiet Technology`,slug: ""},
			B001AMRCDU: {href: "https://amzn.to/2ME4UVR",nameProduct: `Davis Instruments 6152 Vantage Pro2 Wireless Weather Station with Standard Radiation Shield and LCD Display Console`,slug: ""},
			B01MXIMVXG: {href: "https://amzn.to/3joG8F1",nameProduct: `ASICS Men's Gel-Venture 6 Running Shoe`,slug: ""},
			B074FKGR7F: {href: "https://amzn.to/39PD55G",nameProduct: `Epson Home Cinema 2100 1080p 3LCD projector`,slug: ""},
			B003PCSR82: {href: "https://amzn.to/2LkA8R5",nameProduct: `EdgeStar AP14001HS Portable Air Conditioner and Heater with Dehumidifier and Fan for Rooms up to 400 Sq. Ft. with Remote Control`,slug: ""},
			B00R9HVPBK: {href: "https://amzn.to/2MSxnaa",nameProduct: `DHP Emily Futon Couch Bed, Modern Sofa Design Includes Sturdy Chrome Legs and Rich Linen Upholstery, Grey`,slug: ""},
			B002EKUK2C: {href: "https://amzn.to/2YJbj4q",nameProduct: `EdgeStar AP12000HS Portable Air Conditioner and Heater with Dehumidifier and Fan for Rooms up to 250 Sq. Ft. with Remote Control`,slug: ""},
			B00YEYKK8U: {href: "https://amzn.to/3pSdfUi",nameProduct: `OXO BREW 9 Cup Coffee Maker`,slug: ""},
			B00JXS3BXI: {href: "https://amzn.to/3pRNG5I",nameProduct: `Smittybilt 9500 lb 97495 XRC GEN2 Winch-9500 Pound Load Capacity`,slug: ""},
			B075ZZND8B: {href: "https://amzn.to/2YOEuDo",nameProduct: `Hathaspace Smart True HEPA Air Purifier, 5-in-1 Large Room Air Cleaner & Deodorizer for Allergies, Pets, Asthma, Smokers, Odors – Eliminates Pet Hair, Allergens, Dust, Pollen, Mold, Smoke - HSP001`,slug: ""},
			B01LXM1HEK: {href: "https://amzn.to/2YMtJRP",nameProduct: `Zinus Joseph Modern Studio 10 Inch Platforma Low Profile Bed Frame / Mattress Foundation / Boxspring Optional / Wood slat support, Queen`,slug: ""},
			B00G4JCKNG: {href: "https://amzn.to/39Mm6RH",nameProduct: `Safavieh Milan Shag Collection SG180-6060 Aqua Blue Area Rug (5'1" x 8')`,slug: ""},
			B003XELTTG: {href: "https://amzn.to/3pRdpel",nameProduct: `iSpring RCC7 High Capacity Under Sink 5-Stage Reverse Osmosis Drinking Water Filtration System and Ultimate Water Softener`,slug: ""},
			B005Q3VXDY: {href: "https://amzn.to/3cHCS6o",nameProduct: `simplehuman Kitchen Steel Frame Dish Rack With Swivel Spout, Fingerprint-Proof Stainless Steel Frame, Grey Plastic`,slug: ""},
			B07GGF5RFF: {href: "https://amzn.to/2MXGGFW",nameProduct: `Zinus Josh Traditional Upholstered 77.5 Inch Sofa/Living Room Couch, Beige Weave`,slug: ""},
			B00EUKHACW: {href: "https://amzn.to/39ReXj7",nameProduct: `Shark Rocket Ultra-Light Corded Bagless Vacuum for Carpet and Hard Floor Cleaning with Swivel Steering and Car Detail Set (HV302), Gray/Orange`,slug: ""},
			B07GYZS4RJ: {href: "https://amzn.to/39QNvCg",nameProduct: `Stiebel Eltron Tankless Water Heater – Tempra 24 Plus – Electric, On Demand Hot Water, Eco, White`,slug: ""},
			B00IWJOOU8: {href: "https://amzn.to/3jhHAcq",nameProduct: `Briggs & Stratton P3000 PowerSmart Series Inverter Generator with LCD Display and Quiet Power Technology, 3000 Starting Watts 2600 Running Watts, RV Ready`,slug: ""},
			B0777K9RGX: {href: "https://amzn.to/2MXH47m",nameProduct: `Ashley Furniture Signature Design - 12 Inch Chime Express Memory Foam Mattress - Bed in a Box - Queen - Firm Comfort Level - White`,slug: ""},
			B07M8455YG: {href: "https://amzn.to/39QaD3x",nameProduct: `Massage Chair, Zero Gravity Massage Chair, Full Body Massage Chair with Lower-Back Heating and Foot Roller Black`,slug: ""},
			B00FAW4O0A: {href: "https://amzn.to/3oLE4rS",nameProduct: `SoundAsleep Dream Series Air Mattress with ComfortCoil Technology & Internal High Capacity Pump - Queen Size`,slug: ""},
			B00FLYWNYQ: {href: "https://amzn.to/3axMjTg",nameProduct: `Instant Pot Duo 7-in-1 Electric Pressure Cooker, Slow Cooker, Rice Cooker, Steamer, Saute, Yogurt Maker, and Warmer`,slug: ""},
			B004MXKUCY: {href: "https://amzn.to/36LgJ3g",nameProduct: `Simpson Cleaning MSH3125 MegaShot Gas Pressure Washer Powered by Honda GC190, 3200 PSI at 2.5 GPM`,slug: ""},
			B079W93GGX: {href: "https://amzn.to/3aFnNiZ",nameProduct: `Nespresso by De'Longhi EN500W Lattissima One Original Espresso Machine with Milk Frotherby De'Longhi, Silky White`,slug: ""},
			B00D4NPMJE: {href: "https://amzn.to/3pT7ENm",nameProduct: `Fuji 2202 Semi-PRO 2 HVLP Spray System, Blue`,slug: ""},
			B07F3DP48S: {href: "https://amzn.to/2YRXDEc",nameProduct: `Intex 26333EH Ultra XTR Set Above Ground Pool, 20ft X 48in, Gray`,slug: ""},
			B00BWYO53G: {href: "https://amzn.to/3cKQrSA",nameProduct: `Honeywell HPA300 True HEPA Air Purifier, Extra-Large Room, Black`,slug: ""},
			B07C758PD2: {href: "https://amzn.to/2LvJERG",nameProduct: `Shure SE846-CL+BT1 Wireless Sound Isolating Earphones with Bluetooth Enabled Communication Cable, Clear`,slug: ""},
			B009QYC60S: {href: "https://amzn.to/2MWqSmK",nameProduct: `Zojirushi Induction Heating Pressure Rice Cooker & Warmer 1.0 Liter, Stainless Brown NP-NVC10`,slug: ""},
			B07N8VXLW6: {href: "https://amzn.to/3tw039R",nameProduct: `Lounge Chair and Ottoman, Mid Century Modern Classic Design, Natural Leather, High-Density Wood (Black with Red Palisander,Normal 1)`,slug: ""},
			B01DEWZUG4: {href: "https://amzn.to/3tAe46a",nameProduct: `Panasonic Microwave Oven NN-SN686S Stainless Steel Countertop/Built-In with Inverter Technology and Genius Sensor, 1.2 Cu. Ft, 1200W`,slug: ""},
			B01DVQF6EY: {href: "https://amzn.to/36PPk09",nameProduct: `Alesis Strike Pro Kit | Eleven-Piece Professional Electronic Drum Kit with Adjustable Mesh Heads, 110 kits and over 1600 multi-sampled instruments`,slug: ""},
			B002GTCZBA: {href: "https://amzn.to/3cNd9JW",nameProduct: `Sta-Rite SR400NA Max-E-Therm Pool And Spa Heater, Natural Gas, 400,000 BTU`,slug: ""},
			B075JCS7JS: {href: "https://amzn.to/36PFtr9",nameProduct: `Need Computer Desk Office Desk 55 inches Folding Table Computer Table Workstation No Install Needed,Teak Black AC5BB-140X`,slug: ""},
			B07VDH418P: {href: "https://amzn.to/3pWVWBh",nameProduct: `Steelcase Leap Fabric Chair, Black,46216179FBL (Renewed)`,slug: ""},
			B00G7VNO86: {href: "https://amzn.to/36Lr2Eo",nameProduct: `Germ Guardian HEPA Filter Air Purifier with UV Light Sanitizer, Eliminates Germs, Filters Allergies, Pollen, Smoke, Dust, Pet Dander, Mold, Odors, Quiet 4-in-1 Air Purifier for Desk and Office AC4100`,slug: ""},
			B07BNVST4P: {href: "https://amzn.to/3tFB1VZ",nameProduct: `SwagCycle EB-5 Pro Lightweight and Aluminum Folding EBike`,slug: ""},
			B07HK8J2WJ: {href: "https://amzn.to/3jp5VwL",nameProduct: `nakto 26" City Electric Bicycle and Assisted Bicycle for Men with Removable 36V 10A Large Capacity Lithium Battery and Charger`,slug: ""},
			B01D8DAYII: {href: "https://amzn.to/2MGeNCf",nameProduct: `Winix 5500-2 Air Purifier with True HEPA, PlasmaWave and Odor Reducing Washable AOC Carbon Filter`,slug: ""},
			B071D58ZY5: {href: "https://amzn.to/36LS66y",nameProduct: `LEVOIT Air Purifier for Home Smokers Allergies and Pets Hair, True HEPA Filter, Quiet in Bedroom, Filtration System Cleaner Eliminators, Odor Smoke Dust Mold, Night Light, White, LV-H132, 1Pack`,slug: ""},
			B01JKDAN2M: {href: "https://amzn.to/36Lrm64",nameProduct: `Pure Enrichment PureZone Air Purifier 3-in-1 True HEPA Filter with UV-C Sanitizer - Helps Relieve Allergies, Eliminate Germs, Pet Dander, Smoke, Dust & More - Whisper Quiet Operation & Auto Off Timer`,slug: ""},
			B00GPGKN4G: {href: "https://amzn.to/3cQtUUr",nameProduct: `Drive Medical Scout Spitfire 4 Wheel Travel Power Scooter`,slug: ""},
			B01L1TFG66: {href: "https://amzn.to/3aGlKLO",nameProduct: `Z Grills Wood Pellet Grill Smoker with 2019 Newest Digital Controls ,700 Cooking Area 8- in-1 Grill, Smoke, Bake, Roast, Braise ,Sear,Char-grill and BBQ for Outdoor`,slug: ""},
			B0744CTXW8: {href: "https://amzn.to/3aA4Jmm",nameProduct: `Swiss Madison Well Made Forever SM-1T254 St. Tropez One Piece Toilet, 26.6 x 15 x 31 inches, Glossy White`,slug: ""},
			B077416M4M: {href: "https://amzn.to/3tFByqX",nameProduct: `Top Performance Kahuna Superior Massage Chair with SL-Track 6 Rollers - SM-7300 (Black)`,slug: ""},
			B07NMQY3XV: {href: "https://amzn.to/3oRWEhX",nameProduct: `Frigidaire FFRE083ZA1 19" Energy Star Window Mounted Air Conditioner with 8000 BTU Cooling Capacity 115 Volts in White`,slug: ""},
			B004VGIGVY: {href: "https://amzn.to/3ty7gX2",nameProduct: `Germ Guardian True HEPA Filter Air Purifier for Home, Office, Bedrooms, Filters Allergies, Pollen, Smoke, Dust, Pet Dander, UV-C Sanitizer Eliminates Germs, Mold, Odors, Quiet 22 inch 3-in-1 AC4825`,slug: ""},
			B00MYWQL96: {href: "https://amzn.to/2ObQXPo",nameProduct: `Hessaire MC37M portable Evaporative Air Cooler for 950 sq. ft`,slug: ""},
			B00CSGGUUS: {href: "https://amzn.to/36Nbmkm",nameProduct: `Global Air 10,000 BTU Portable Air Conditioner Cooling /Fan with Remote Control in White`,slug: ""},
			B003R3JFJO: {href: "https://amzn.to/3cM2CP2",nameProduct: `BISSELL Garage Pro Wall-Mounted Wet Dry Car Vacuum/Blower with Auto Tool Kit, 18P03-Gray, Gray`,slug: ""},
			B07GB3FNNV: {href: "https://amzn.to/3pY9Y5L",nameProduct: `Instant Pot Aura Multi-Use Programmable Slow Cooker, 6 Quart, No Pressure Cooking Functionality`,slug: ""},
			B0792BWMV4: {href: "https://amzn.to/3btoFrH",nameProduct: `Roborock S5 Robotic Vacuum and Mop Cleaner, 2000Pa Super Power Suction &Wi-Fi Connectivity and Smart Navigating Robot Vacuum with 5200mAh Battery Capacity for Pet Hair, Carpet & Hard Floor (White)`,slug: ""},
			B01D8DAYBA: {href: "https://amzn.to/2NpJkET",nameProduct: `Winix 5300-2 Air Purifier with True HEPA, PlasmaWave and Odor Reducing Carbon Filter`,slug: ""},
			B01923E15A: {href: "https://amzn.to/2M8Iwnb",nameProduct: `Avallon ABR241SGRH 140 Can 24" Built-in Beverage Cooler - Right Hinge`,slug: ""},
			B072PZ4LVN: {href: "https://amzn.to/3dCSF7b",nameProduct: `Rivet Revolve Modern Upholstered Sofa Couch, 80"W, Grey Weave`,slug: ""},
			B00HQONFY6: {href: "https://amzn.to/3bobk3M",nameProduct: `WEN 4214 12-Inch Variable Speed Drill Press`,slug: ""},
			B01C9RIACG: {href: "https://amzn.to/3bmgbCB",nameProduct: `Coway Airmega 400 Smart Air Purifier with 1,560 sq. ft. Coverage`,slug: ""},
			B0026SR0FW: {href: "https://amzn.to/3qIbI3E",nameProduct: `Graco Magnum 262800 X5 Stand Airless Paint Sprayer`,slug: ""},
			B06XFVQFP9: {href: "https://amzn.to/3keY19W",nameProduct: `LG LW6017R 6,000 BTU 115V Window Air Conditioner, 6000, White (Not an Energy Star)`,slug: ""},
			B0792PD6TY: {href: "https://amzn.to/3uksWpE",nameProduct: `Woodbridge b-0030/bts1606 67" x 32" Whirlpool Water Jetted and Air Bubble Freestanding Bathtub, B-0030 / BTS1606`,slug: ""},
			B01MPX171W: {href: "https://amzn.to/3az74zc",nameProduct: `Braun Electric Razor for Men, Series 7 7865cc Electric Shaver with Precision Trimmer, Rechargeable, Wet & Dry Foil Shaver, Clean & Charge Station and Travel Case`,slug: ""},
			B073VBWKJZ: {href: "https://amzn.to/3qDUlRp",nameProduct: `hOmeLabs 4,500 Sq. Ft Energy Star Dehumidifier for Extra Large Rooms and Basements - Efficiently Removes Moisture to Prevent Mold, Mildew and Allergens`,slug: ""},
			B07F2H3NL8: {href: "https://amzn.to/2ZzcgNd",nameProduct: `WOODBRIDGE 59" Acrylic Freestanding Bathtub Contemporary Soaking Tub with Chrome Overflow and Drain, B-0018 / BTA1518, Oval`,slug: ""},
			B07KQ6S5N1: {href: "https://amzn.to/2M9NMaj",nameProduct: `Cordless Vacuum, ONSON Stick Vacuum Cleaner, 12KPa Powerful Cleaning Lightweight Handheld Vacuum with Rechargeable Lithium Ion Battery`,slug: ""},
			B00F2CGXGG: {href: "https://amzn.to/2ZFSyzb",nameProduct: `DEWALT (DWE7491RS) 10-Inch Table Saw, 32-1/2-Inch Rip Capacity`,slug: ""},
			B00SMNLF4M: {href: "https://amzn.to/2Nozlja",nameProduct: `WEN 56200i Super Quiet 2000-Watt Portable Inverter Generator, CARB Compliant`,slug: ""},
			B07CZ1CF79: {href: "https://amzn.to/2M7wB9a",nameProduct: `Arctic Dreams 10" Hybrid Cooling Gel Mattress with Quick Response Gel Infused Memory Foam, Made in The USA, Twin XL`,slug: ""},
			B07BWN72TW: {href: "https://amzn.to/3kbjMal",nameProduct: `Camp Chef SmokePro DLX PG24 Pellet Grill with Patio Cover - Bundle (Full Cover)`,slug: ""},
			B07BN3MB6Z: {href: "https://amzn.to/37wyrI3",nameProduct: `FRIGIDAIRE 10,000 BTU 115V Window-Mounted Compact Temperature Sensing Remote Control, White Air Conditioner`,slug: ""},
			B07NBNCNLM: {href: "https://amzn.to/3pGHoFc",nameProduct: `VANKYO Performance V600 Native 1080P LED Projector, 6000 Lux HDMI Projector with 300" Display Compatible with TV Stick, HDMI, VGA, USB, Laptop, iPhone Android for PowerPoint Presentation`,slug: ""},
			B07NC8ZDVL: {href: "https://amzn.to/3s9u9hG",nameProduct: `Samsung UN75RU7100FXZA Flat 75-Inch 4K UHD 7 Series Ultra HD Smart TV with HDR and Alexa Compatibility (2019 Model)`,slug: ""},
			B00CMREO0Q: {href: "https://amzn.to/37AakIA",nameProduct: `Touchstone 80001 - Onyx Electric Fireplace - (Black) - 50 Inch Wide - On-Wall Hanging - Log & Crystal Included - 5 Flame Settings - Realistic Flame - 1500/750W Timer & Remote`,slug: ""},
			B00198CW7G: {href: "https://amzn.to/3scnun2",nameProduct: `Hayward SP2610X15 Super Pump 1.5 HP Pool Pump`,slug: ""},
			B01LWA8J37: {href: "https://amzn.to/3bqaOSX",nameProduct: `AlorAir Basement/Crawl space Dehumidifiers Removal 120 PPD (Saturation) 55 PPD (AHAM)`,slug: ""},
			B07V48X7HG: {href: "https://amzn.to/3sfHsx8",nameProduct: `LG, LW1019IVSM Energy Star 9,500 BTU 115V Dual Inverter Window Air Conditioner with Wi-Fi Control`,slug: ""},
			B00G0PF4FU: {href: "https://amzn.to/2ZAazzd",nameProduct: `Whynter 8,000 BTU Eco-Friendly Portable Air Conditioner, White (ARC-08WB)`,slug: ""},
			B01AA8WOAK: {href: "https://amzn.to/3dvp3Zj",nameProduct: `Whynter Elite ARC-122DS 12,000 BTU Dual Hose Portable Air Conditioner`,slug: ""},
			B07KKFDM1M: {href: "https://amzn.to/3aD9sor",nameProduct: `CRAFTSMAN V60 Cordless Leaf Blower (CMCBL760E1)`,slug: ""},
			B07P1XFYJP: {href: "https://amzn.to/3qSW4Cg",nameProduct: `Waterdrop RO Reverse Osmosis Water Filtration System, TDS Reduction, 400 GPD Fast Flow, Tankless, Smart Faucet, UL Listed Power Cord, 1: 1 Drain Ratio, USA Tech Support`,slug: ""},
			B072BZBPXP: {href: "https://amzn.to/2ZDTWme",nameProduct: `Innova ITM5900 Advanced Heat and Massage Inversion Therapy Table`,slug: ""},
			B07KKC6JP8: {href: "https://amzn.to/2ZBGcbr",nameProduct: `CRAFTSMAN V60 3-in-1 Cordless Lawn Mower, 21-Inch (CMCMW260P1)`,slug: ""},
			B06X415RY6: {href: "https://amzn.to/2ZzDsv5",nameProduct: `Craftman V60 Cordless 15-in. Brushlessa Weedwacker String Trimmer with Quickwing Kit(2.5AH)`,slug: ""},
			B0009RF7DY: {href: "https://amzn.to/2Mffmmy",nameProduct: `Shoprider Sunrunner 4 Wheel Scooter`,slug: ""},
			B075CQ86ZV: {href: "https://amzn.to/2ZzuwpN",nameProduct: `Chamberlain Group Chamberlain B970 Smartphone-Controlled Ultra-Quiet & Strong Belt Drive Garage Door Opener with Battery Backup and MAX Lifting Power, Blue`,slug: ""},
			B0713TGHVM: {href: "https://amzn.to/3qCrT2e",nameProduct: `Essential Hot Tubs 11-Jet Integrity Hot Tub, Seats 4-5, Cobblestone`,slug: ""},
			B00H2VOSP8: {href: "https://amzn.to/3sfkWoh",nameProduct: `Corentium Home Radon Detector by Airthings 223 Portable, Lightweight, Easy-to-Use, (3) AAA Battery Operated, USA Version, pCi/L`,slug: ""},
			B00I0ZGOZM: {href: "https://amzn.to/3brKCan",nameProduct: `APEC Top Tier 5-Stage Ultra Safe Reverse Osmosis Drinking Water Filter System (ESSENCE ROES-50)`,slug: ""},
			B005NASZG8: {href: "https://amzn.to/3dzrj1G",nameProduct: `Hoover Commercial Lightweight Backpack Vacuum, C2401`,slug: ""},
			B0116W5B5O: {href: "https://amzn.to/3scaJcc",nameProduct: `La-Z-Boy Delano Big & Tall Executive Bonded Leather Office Chair - Chestnut (Brown)`,slug: ""},
			B01N5SMNJ4: {href: "https://amzn.to/3kwlSC2",nameProduct: `Hoover Power Scrub Elite Pet Carpet Cleaner, FH50251`,slug: ""},
			B071RP2PVY: {href: "https://amzn.to/3aZsNjP",nameProduct: `Portable Washing Machine, Spin Dryer-Compact Twin Tub Durable Design 9.9lbs Mini Washer to Wash All your Laundry for Apartments, Dorms, RV Camping Swim Suit Spinner Dryer, Blue`,slug: ""},
			B00UWP07LK: {href: "https://amzn.to/3bO4xjR",nameProduct: `Frigidaire 70-Pint Dehumidifier with Effortless Humidity Control, White`,slug: ""},
			B016PXH9R2: {href: "https://amzn.to/3r1nNAR",nameProduct: `PetSafe ScoopFree Ultra Self-Cleaning Cat Litter Box, Covered, Automatic with Disposable Tray, 2 Color Options`,slug: ""},
			B01CA4PRBA: {href: "https://amzn.to/2NJF5UI",nameProduct: `Greenworks 1600 PSI 13 Amp 1.2 GPM Pressure Washer GPW1602`,slug: ""},
			B075XQRXCF: {href: "https://amzn.to/37WHpih",nameProduct: `Portable Washing Machine TG23 - Twin Tub Washer Machine with Wash and Spin Cycle Compartments by ThinkGizmos (Trademark Protected)`,slug: ""},
			B07B4YXMK9: {href: "https://amzn.to/3reWhjL",nameProduct: `Essential Hot Tubs 67 Jets Syracuse Lounger, Rotationally Molded Hot Tub, Espresso`,slug: ""},
			B009SCPYN4: {href: "https://amzn.to/3st1Hrk",nameProduct: `Hudson Bay Spas 4 Person 14 Jet Spa with Stainless Jets and 110V GFCI Cord Included`,slug: ""},
			B07DJ2Y4PJ: {href: "https://amzn.to/3st1Hrk",nameProduct: `Phiestina 24 Inch Built In Dual Zone Wine and Beverage Cooler with French Door`,slug: ""},
			B0787BVSTH: {href: "https://amzn.to/3sBOmgG",nameProduct: `LUNA Weighted Blanket (15 lbs - 60x80 - Queen Size) – Organic Cooling Cotton & Premium Glass Beads – Designed in USA – Heavy Cool Weighted Blanket for Hot & Cold Sleepers – Kids or Adult – Grey`,slug: ""},
			B00BRUNPXQ: {href: "https://amzn.to/3uBZWtL",nameProduct: `Sauder August Hill L-Shaped Desk, L: 59.06" x W: 58.74" x H: 29.25", Dover Oak finish`,slug: ""},
			B0100RBPTC: {href: "https://amzn.to/3bMeaj9",nameProduct: `Casio Privia PX-160BK 88-Key Full Size Digital Piano with Power Supply, Black`,slug: ""},
			B002G51BZU: {href: "https://amzn.to/3bQeJst",nameProduct: `Mr. Heater F232000 MH9BX Buddy 4,000-9,000-BTU Indoor-Safe Portable Propane Radiant Heater`,slug: ""},
			B01EAG9XLG: {href: "https://amzn.to/3uEEzrT",nameProduct: `Sleep Innovations Shea 10-inch Memory Foam Mattress, Bed in a Box, Made in the USA, 10-Year Warranty - Queen Size`,slug: ""},
			B01ET84Y46: {href: "https://amzn.to/3b1ij3J",nameProduct: `Modway Aveline 8" Gel Infused Memory Foam Full Mattress With CertiPUR-US Certified Foam - 10-Year Warranty - Available In Multiple Sizes`,slug: ""},
			B06W2GYD8Y: {href: "https://amzn.to/3uEIzsj",nameProduct: `Real Relax Massage Chair, Full Body Zero Gravity Shiatsu Recliner with Heat and Foot Rollers, Black`,slug: ""},
			B00QRJALYI: {href: "https://amzn.to/37TfVKr",nameProduct: `Delta Faucet Leland Single-Handle Touch Kitchen Sink Faucet with Pull Down Sprayer, Touch2O and ShieldSpray Technology, Magnetic Docking Spray Head, Arctic Stainless 9178T-AR-DST`,slug: ""},
			B07QQW19BP: {href: "https://amzn.to/3uCgi5H",nameProduct: `Massage Chair by OOTORI,3D SL-Track Thai Yoga Stretching Zero Gravity Massage Chair,Full Body Shiatsu Massage Chairs Recliner with Tapping, Heating and Foot Roller Massager (Black)`,slug: ""},
			B00005RHPD: {href: "https://amzn.to/3ku0Hk5",nameProduct: `Bosch 1617EVSPK Wood Router Tool Combo Kit - 2.25 Horsepower Plunge Router & FIXED Base Router Kit with A Variable Speed 12 Amp Motor`,slug: ""},
			B00AB25016: {href: "https://amzn.to/3stXUtK",nameProduct: `Dri-Eaz F284 DefendAir HEPA 500 Air Purifier Negative Air Machine Air Scrubber`,slug: ""},
			B073WJL99W: {href: "https://amzn.to/3stiBWO",nameProduct: `Blue Pure 211+ Air Purifier 3 Stage with Two Washable Pre-Filters, Particle, Carbon Filter, Captures Allergens, Odors, Smoke, Mold, Dust, Germs, Pets, Smokers, Large Room`,slug: ""},
			B007HIKQCK: {href: "https://amzn.to/3dUavT9",nameProduct: `Bio Bidet Ultimate BB-600 Advanced Bidet Toilet Seat, Elongated White. Easy DIY Installation, Luxury Features From Side Panel, Adjustable Heated Seat and Water. Dual Nozzle Has Posterior and Feminine Wash`,slug: ""},
			B001BMDFPS: {href: "https://amzn.to/300woYR",nameProduct: `DuroMax XP4400E 4,400 Watt 7.0 HP OHV 4-Cycle Gas Powered Portable Generator With Wheel Kit And Electric Start`,slug: ""},
			B06VSJ9D1H: {href: "https://amzn.to/3bKToQT",nameProduct: `BISSELLProHeat 2X Revolution Max Clean Pet Pro Full-Size Carpet Cleaner, 1986`,slug: ""},
			B016XMU2OC: {href: "https://amzn.to/2ZVghvF",nameProduct: `Backyard Discovery Woodland All Cedar Wood Playset Swing Set`,slug: ""},
			B07FPY2GL8: {href: "https://amzn.to/3swTna8",nameProduct: `Medical Breakthrough 6 v4 Recliner 3D Massage Chair | Zero Gravity with Heating | Deep Tissue Shiatsu Full Body Massager | Yoga Stretch | Pain Relief | Full Foot Massager | Perfect Luxury Gift (Black)`,slug: ""},
			B002ZDAEIS: {href: "https://amzn.to/31ZWImU",nameProduct: `Razor EcoSmart Metro Electric Scooter`,slug: ""},
			B0193V3DJ6: {href: "https://amzn.to/325SB8F",nameProduct: `NordicTrack T 6.5 Series`,slug: ""},
			B07FTN21JL: {href: "https://amzn.to/3myXX5L",nameProduct: `Fitbit Charge 3 Fitness Activity Tracker`,slug: ""},
			B07144LZ9V: {href: "https://amzn.to/2PH9nZw",nameProduct: `Best Choice Products Portable Mini Twin Tub Compact Washing Machine w/Spin Dry Cycle, 18lb Load Capacity`,slug: ""},
			B001EQ45OG: {href: "https://amzn.to/31ZeIOe",nameProduct: `American Standard 2461002.011 Cambridge Apron-Front Americast Soaking Bathtub Right Hand Drain, 5 ft x 32 in, Arctic`,slug: ""},
			B00450U6CS: {href: "https://amzn.to/3wI8kZW",nameProduct: `Bissell Big Green Professional Carpet Cleaner Machine, 86T3`,slug: ""},
			B001CNG7RY: {href: "https://amzn.to/3s3bRhQ",nameProduct: `DeLonghi EC702 15-Bar-Pump Espresso Maker, Stainless, Metal`,slug: ""},
			B074MLZR3Y: {href: "https://amzn.to/322Wpre",nameProduct: `Brondell Swash Non-Electric Seat, Fits Round Toilets, White – Dual Nozzle System, Ambient Water Temperature – Bidet with Easy Installation`,slug: ""},
			B00PHNFML2: {href: "https://amzn.to/2OCVRFI",nameProduct: `Breville BFP660SIL Sous Chef 12 Cup Food Processor, Silver`,slug: ""},
			B00K150VAI: {href: "https://amzn.to/31WrrRK",nameProduct: `Smittybilt (98510) X2O Waterproof Synthetic Rope Winch - 10000 lb. Load Capacity`,slug: ""},
			B005EFYCNW: {href: "https://amzn.to/3mEg4Yb",nameProduct: `Sauder Home Plus Storage Cabinet, Dakota Oak finish`,slug: ""},
			B07GYP68HW: {href: "https://amzn.to/3wFWY8y",nameProduct: `Epson Home Cinema 4010 4K PRO-UHD (1) 3-Chip Projector with HDR`,slug: ""},
			B0144DQNWW: {href: "https://amzn.to/3wP1qSP",nameProduct: `Ultra HD Mega Storage Cabinet - Stainless Steel`,slug: ""},
			B075FGY7G2: {href: "https://amzn.to/3wP1sKr",nameProduct: `Zinus Suzanne Metal and Wood Platform Bed with Headboard / Box Spring Optional / Wood Slat Support, Queen`,slug: ""},
			B07B94ZR74: {href: "https://amzn.to/3d4VzAW",nameProduct: `SUPER DEAL Portable Washer Mini Twin Tub Washing Machine 17.6 lbs w/78.8'' Inlet Hose, Gravity Drain Pump, For Camping, Apartments, Dorms, College Rooms, RV's, Delicates and more`,slug: ""},
			B0067MQM48: {href: "https://amzn.to/3s0NdOH",nameProduct: `Zojirushi BB-PAC20BA BB-PAC20 Home Bakery Virtuoso Breadmaker with Gluten Free Menu setting`,slug: ""},
			B01B8GQ940: {href: "https://amzn.to/3uCao3C",nameProduct: `Zinus Mia Modern Studio 14 Inch Platform 1500H Metal Bed Frame / Mattress Foundation / Wooden Slat Support / With Headboard / Good Design Award Winne`,slug: ""},
			B07XF9NYV3: {href: "https://amzn.to/2Rmgx5R",nameProduct: `Zmodo 1080p Full HD Outdoor Wireless Security Camera System, 4 Pack Smart Home Indoor Outdoor WiFi IP Cameras with Night Vision, Compatible with Alexa`,slug: ""},
			B000XRQUSQ: {href: "https://amzn.to/2PQOgUz",nameProduct: `Krinner Tree Genie Tree Genie XXL Christmas Tree Stand, Green`,slug: ""},
			B076CPZWR3: {href: "https://amzn.to/3t5LJEa",nameProduct: `Sauder HomePlus Storage Cabinet`,slug: ""},
			B00T9RANUC: {href: "https://amzn.to/2PENoSZ",nameProduct: `FLIR C2 - Compact Thermal Camera`,slug: ""},
			B071FN6KXK: {href: "https://amzn.to/3wAzO3D",nameProduct: `Osmo Genius Kit for iPad`,slug: ""},
			B07MSYTQNM: {href: "https://amzn.to/39W0wd3",nameProduct: `Fitbit Inspire HR Heart Rate & Fitness Tracker`,slug: ""},
			B07L6LB6LR: {href: "https://amzn.to/3wQS2xY",nameProduct: `Brooks Men's Ghost 12`,slug: ""},
			B002FQIYBY: {href: "https://amzn.to/3uETTUn",nameProduct: `Pentair 340039 SuperFlo High Performance Single Speed Pool Pump, 1½ Horsepower, 115/230 Volt, 1 Phase`,slug: ""},
			B072MLT6QW: {href: "https://amzn.to/3dKq7XO",nameProduct: `Dometic CFX 50W 12v Electric Powered Portable Cooler, Fridge Freezer`,slug: ""},
			B07D8QGJ5V: {href: "https://amzn.to/3s0iq4F",nameProduct: `Desire Life Yoga Headstand Bench - Stand Yoga Chair for Family, Gym - Wood and PU Pads - Relieve Fatigue and Build Up Body`,slug: ""},
			B07H5RVVM6: {href: "https://amzn.to/3uChB3G",nameProduct: `Black + Decker BPWM09W Portable Washer`,slug: ""},
			B07GPXKN8Z: {href: "https://amzn.to/2PGaGId",nameProduct: `Flume Water Monitor: Smart Home Water Monitoring to Detect Leaks & Track Water Usage in Real Time. Compatible with Alexa`,slug: ""},
			B01M7M9NXX: {href: "https://amzn.to/3t4sI5e",nameProduct: `Zinus Shalini Upholstered Diamond Stitched Platform Bed / Mattress Foundation / Easy Assembly / Strong Wood Slat Support / Dark Grey, Queen`,slug: ""},
			B07GH8DNZN: {href: "https://amzn.to/3t6po9D",nameProduct: `Calphalon Special Brew 10 Cup Coffee Maker, Dark Stainless Steel`,slug: ""},
			B01J664WSY: {href: "https://amzn.to/2OEGInm",nameProduct: `Vornado VMH600 Whole Room Stainless Steel Heater with Auto Climate Control and Remote`,slug: ""},
			B016OIF2JU: {href: "https://amzn.to/3d01Z4b",nameProduct: `Steelcase Gesture Chair, Graphite`,slug: ""},
			B07FFMTW8X: {href: "https://amzn.to/3t8Q75u",nameProduct: `Tineco A11 Master+ Cordless Stick Vacuum Cleaner, Ultra Powerful Suction, Multi-Surface Cleaning, Great for Pet Hair, Emerald Green`,slug: ""}
		}
	}
	return dataAMZ;
}
