function getData(){
	const keysw = "www.groovybest.com";
	var keyAPI = (typeof keyhost != 'undefined') ? keyhost : document.location.host;
	var dataAMZ = {};
	if(keysw == keyAPI){
		dataAMZ = {
			B01ALBMIEI: {href: "https://amzn.to/39p1f6i",nameProduct: `Giantex Portable Mini Compact Twin Tub Washing Machine 17.6lbs Washer Spain Spinner, Blue+ White`,slug: ""},
			B01KIMOEW4: {href: "https://amzn.to/2Phvc1g",nameProduct: `Hoover Spotless Portable Carpet & Upholstery Spot Cleaner, FH11300PC`,slug: ""},
			B07NHVFWCQ: {href: "https://amzn.to/3crv34m",nameProduct: `Panda Full-Automatic Portable Machine, 1.34 Cu.ft,10lbs Capacity, Light Gray, PAN56MGP3, 10 Wash Programs, Compact Top Load Cloth Washer`,slug: ""},
			B078HFRNPQ: {href: "https://amzn.to/3ctsq1S",nameProduct: `Blackstone 1825 36" Accessory Griddle with Side Shelf, 36 inch-4 Burner-W/New`,slug: ""},
			B07B94ZR74: {href: "https://amzn.to/2O2VGDi",nameProduct: `SUPER DEAL Portable Compact Mini Twin Tub Washing Machine w/Wash and Spin Cycle, Built-in Gravity Drain, 13lbs Capacity For Camping, Apartments, Dorms, College Rooms, RV’s, Delicates and more`,slug: ""},
			B07BD2G4TY: {href: "https://amzn.to/39mv5bJ",nameProduct: `ZENY Portable Mini Twin Tub Washing Machine 13lbs Capacity with Spin Dryer,Compact Cloths Washing Machine Lightweight Small Laundry Washer for Home,Apartments, Dorm Rooms,RV's`,slug: ""},
			B0028AYQDC: {href: "https://amzn.to/3lYmG3e",nameProduct: `Whynter ARC-14S 14,000 BTU Dual Hose Portable Air Conditioner, Dehumidifier, Fan with Activated Carbon Filter Plus Storage Bag for Rooms up to 500 sq ft, Platinum and Black`,slug: ""},
			B000BQMV0A: {href: "https://amzn.to/3ctsDSI",nameProduct: `Reflectix DW1202504 Spiral Duct Wrap, Silver`,slug: ""},
			B000BQRBB4: {href: "https://amzn.to/3w6JPp2",nameProduct: `Reflectix FT210 Reflective Foil Tape, 2" x 30'`,slug: ""},
			B01ICBLBL0: {href: "https://amzn.to/3lX6FKQ",nameProduct: `Best Choice Products Portable Compact Mini Twin Tub Laundry Washing Machine and Spin Cycle Dryer w/Hose, 13lbs Load Capacity, Built-In Drain - White/Blue`,slug: ""},
			B07C76PV28: {href: "https://amzn.to/3lYXVUx",nameProduct: `Honeywell MO10CESWK Compact 3-in-1 Portable Air Conditioner w/ Remote Control, Up to 450 Sq. Ft., White/Black`,slug: ""},
			B07J6S4RZ9: {href: "https://amzn.to/39lSl9S",nameProduct: `ZENY Portable Compact Washing Machine Mini Twin Tub Washer Spin Spinner 9.9lbs Capacity, Lightweight Small Laundry Washer for Apartment RV`,slug: ""},
			B079BZHVGV: {href: "https://amzn.to/3lWie5d",nameProduct: `Lemi Shine 100% Natural Citric Extracts Laundry Detergent Booster Liquid, 3-Bottles of 32 fl oz`,slug: ""},
			B085NYQ9ZC: {href: "https://amzn.to/3cuhdOH",nameProduct: `Honeywell, MN12CEDWW 12,000 BTU Air Portable Conditioner with Dual Hose, 12000, White`,slug: ""},
			B07NBKGNJ2: {href: "https://amzn.to/3u3Hn0K",nameProduct: `KUPPET Portable Compact Mini Washing Machine,Twin Tub 26.4 lbs Capacity,Washer(17.6lbs)&Spiner(8.8lbs),Built-in Drain Pump/Semi-Automatic，(White&Blue)`,slug: ""},
			B07TDP2MMQ: {href: "https://amzn.to/3suyfln",nameProduct: `KUPPET Compact Twin Tub Portable Mini Washing Machine 26lbs Capacity, Washer(18lbs)&Spiner(8lbs)/Built-in Drain Pump/Semi-Automatic (White&Gray)`,slug: ""},
			B071RZXXZ9: {href: "https://amzn.to/3wgMpsC",nameProduct: `Philips Norelco MG5750/49 Multigroom All-In-One Trimmer Series 5000 With 18Piece, No Blade Oil Needed,`,slug: ""},
			B01DTYAZO4: {href: "https://amzn.to/31o3WAV",nameProduct: `BISSELL Crosswave All in One Wet Dry Vacuum Cleaner and Mop for Hard Floors and Area Rugs, 1785A, Green`,slug: ""},
			B07144LZ9V: {href: "https://amzn.to/3w6hTS5",nameProduct: `Best Choice Products Portable Mini Twin Tub Compact Washing Machine and Dryer Combo, 18-Pound Load Capacity, w/ 15-Minute Timer, Drain Hose, Spin Dry Cycle, White/Blue`,slug: ""},
			B06WP2CLYY: {href: "https://amzn.to/2PcHQid",nameProduct: `BISSELL Spinwave Powered Hardwood Floor Mop and Cleaner, Green Spinwave`,slug: ""},
			B07238W469: {href: "https://amzn.to/3rvSei0",nameProduct: `JHS 12,000 BTU Portable Air Conditioner, 3-in-1 Floor AC Unit with 3 Fan Speeds, Remote Control and Digital LED Display, Cover up to 400 Sq. Ft.`,slug: ""},
			B07PW66ZSN: {href: "https://amzn.to/31sF0bw",nameProduct: `COLZER 140 Pints Commercial Dehumidifier Large Capacity Dehumidifiers for Basements, Showrooms, Gallery, Storage Rooms, Warehouse, Build-in 17-Pint Water Tank and 6.6 ft. Drain Hose`,slug: ""},
			B07MXDRTKJ: {href: "https://amzn.to/3w5zMQX",nameProduct: `COLZER 70 Pints Home Dehumidifiers for 4,500 SQ FT Basements & Large Rooms, Large Removal Capacity with 7.4-Pint Water Bucket & Continuous Drain Hose for Self-draining`,slug: ""},
			B07Q55RYK8: {href: "https://amzn.to/2PdbeVA",nameProduct: `Inofia Air Purifier With True HEPA Air Filter, Wi-Fi Intelligent Control, Air Cleaner For Large Room, For Spaces Up To 1056 Sq Ft, Dust, Smoke, Pets dander, Smokers, Perfect For Home/Office`,slug: ""},
			B06XKDYD4S: {href: "https://amzn.to/3ryN19g",nameProduct: `Giantex 16lbs Portable Mini Washing Machine Gravity Drain Compact Twin Tub Washer Spinner, Ideal for Dorms, Apartments, RVs, Camping`,slug: ""},
			B07V56QH7T: {href: "https://amzn.to/39od64D",nameProduct: `Hathaspace Smart True HEPA Air Purifier 2.0 for Extra-Large Rooms with Medical Grade H13 HEPA Filter, 5-in-1 Home Air Cleaner for Allergies, Asthma, Pets, Odors, Smokers, 1500+ Sq Ft Coverage - HSP002`,slug: ""},
			B00Q8M0NWE: {href: "https://amzn.to/3fiifiw",nameProduct: `Dolphin Nautilus CC Plus Automatic Robotic Pool Cleaner with Easy To Clean Large Top Load Filter Cartridges and Tangle-Free Swivel Cord, Ideal for In-Ground Swimming Pools Up To 50 Feet`,slug: ""},
			B01N3CCOZ3: {href: "https://amzn.to/2PASzTo",nameProduct: `Leesa Luxury Hybrid 11 Inch Mattress, Innerspring and Premium Foam, King`,slug: ""},
			B076MJFKVG: {href: "https://amzn.to/31qL2cy",nameProduct: `Brooklyn Signature 11" Hybrid Mattress with Patented TitanFlex Pressure Relieving Foam, Queen Medium`,slug: ""},
			B0876HX533: {href: "https://amzn.to/39k8PPy",nameProduct: `The Purple Mattress (Queen)`,slug: ""},
			B0889GW1VP: {href: "https://amzn.to/3suz9ON",nameProduct: `Nectar Full Mattress - 365 Night Home Trial - Gel Memory Foam Mattress - CertiPUR-US Certified Foams - Forever Warranty`,slug: ""},
			B00RDITBSY: {href: "https://amzn.to/3w4P0FO",nameProduct: `Leesa Original Bed-in-a-Box, Three Premium Foam Layers Mattress, King, Gray & White`,slug: ""},
			B079TGL2BZ: {href: "https://amzn.to/3dihtQ5",nameProduct: `Acer Aspire E 15, 15.6" Full HD, 8th Gen Intel Core i3-8130U, 6GB RAM Memory, 1TB HDD, 8X DVD, E5-576-392H`,slug: ""},
			B00G7RHGNY: {href: "https://amzn.to/2PgGT8D",nameProduct: `PowerBlock Elite Dumbbells`,slug: ""},
			B01MRNXXYQ: {href: "https://amzn.to/39nJ4xT",nameProduct: `Sunny Health & Fitness Folding Compact Motorized Treadmill - LCD Display, Shock Absorption and 220 LB Max Weight - SF-T7632,Gray`,slug: ""},
			B001G60JA8: {href: "https://amzn.to/39nX0bf",nameProduct: `SOLE F63 Treadmill`,slug: ""},
			B075VCM1XR: {href: "https://amzn.to/3u3Ia1I",nameProduct: `ZINUS Dori Upholstered Platform Bed Frame with Wingback Headboard / Mattress Foundation / Wood Slat Support / No Box Spring Needed / Easy Assembly, Queen`,slug: ""},
			B00PQA3GX2: {href: "https://amzn.to/31qpqwT",nameProduct: `Safavieh Hudson Shag Collection SGH280A Moroccan Ogee 2-inch Thick Area Rug, 2' x 3', Ivory/Grey`,slug: ""},
			B01M7X9PIG: {href: "https://amzn.to/3fyuFTJ",nameProduct: `WARN 96815 VR10-S Electric 12V Winch with Synthetic Rope: 3/8" Diameter x 90' Length, 5 Ton (10,000 lb) Pulling Capacity`,slug: ""},
			B07BQL8L1K: {href: "https://amzn.to/39kVC9t",nameProduct: `Zinus Benton, Sofa, Stone Grey`,slug: ""},
			B07F2H3NL8: {href: "https://amzn.to/2QKu0Ee",nameProduct: `Woodbridge 59" Acrylic Freestanding Bathtub Contemporary Soaking Tub with Brushed Nickel Overflow and Drain, Oval`,slug: ""},
			B06XMY9D5K: {href: "https://amzn.to/2Pwp9Wy",nameProduct: `Zinus Paul Metal and Wood Platform Bed with Wood Slat Support, Queen`,slug: ""},
			B016J0EITS: {href: "https://amzn.to/3sxfCNs",nameProduct: `SureFire X300 Ultra Series LED WeaponLights with TIR Lens`,slug: ""},
			B07GZN3QNZ: {href: "https://amzn.to/31olM6z",nameProduct: `Inofia 8 inch Hybrid Comfort Eurotop Innerspring Mattress- Plush Yet Supportive-Pressure Relief, Twin Size`,slug: ""},
			B01MXNLIET: {href: "https://amzn.to/3u1Xtrq",nameProduct: `Reverie 5 Series Adjustable Bed, Wall-Hugger, Wireless, HD Massage, Zero-Gravity, Memory Positions`,slug: ""},
			B06W2GYD8Y: {href: "https://amzn.to/2QD02BS",nameProduct: `Real Relax 2020 Massage Chair, Full Body Zero Gravity Shiatsu Recliner with Bluetooth and Led Light, Black`,slug: ""},
			B00QRJALYI: {href: "https://amzn.to/3csMXDz",nameProduct: `Delta Faucet Leland Single-Handle Touch Kitchen Sink Faucet with Pull Down Sprayer, Touch2O and ShieldSpray Technology, Magnetic Docking Spray Head, Arctic Stainless 9178T-AR-DST`,slug: ""},
			B001LZRF9M: {href: "https://amzn.to/3dhAzFI",nameProduct: `EcoSmart ECO 11 Electric Tankless Water Heater, 13KW at 240 Volts with Patented Self Modulating Technology`,slug: ""},
			B01N80F68E: {href: "https://amzn.to/2QLpzsN",nameProduct: `Westinghouse WGen7500 Portable Generator with Remote Electric Start 7500 Rated Watts & 9500 Peak Watts, Gas Powered, CARB Compliant, Transfer Switch Ready`,slug: ""},
			B07JYXZ6VJ: {href: "https://amzn.to/39kglKm",nameProduct: `VIVOHOME 110V Electric Fireplace Insert Log Quartz Realistic Ember Bed Fan Heater with Infrared Remote Controller Black`,slug: ""},
			B074F8TZNH: {href: "https://amzn.to/3df1jXn",nameProduct: `Brother SE600 Sewing and Embroidery Machine, 80 Designs, 103 Built-In Stitches, Computerized, 4" x 4" Hoop Area, 3.2" LCD Touchscreen Display, 7 Included Feet`,slug: ""},
			B00UHNM1R0: {href: "https://amzn.to/3dii7Nv",nameProduct: `BOSTITCH Pancake Air Compressor, Oil-Free, 6 Gallon, 150 PSI (BTFP02012)`,slug: ""},
			B006UKLUFS: {href: "https://amzn.to/3fkqavG",nameProduct: `Cuisinart ICE-100 Compressor Ice Cream and Gelato Maker, Silver, 1-1/2-Quart`,slug: ""},
			B089YSKJY6: {href: "https://amzn.to/3svV6gk",nameProduct: `COMFEE’ 1.6 Cu.ft Portable Washing Machine, 11lbs Capacity Fully Automatic Compact Washer with Wheels, 6 Wash Programs Laundry Washer with Drain Pump, Ideal for Apartments, RV, Camping, Magnetic Gray`,slug: ""},
			B005Q3VXDY: {href: "https://amzn.to/3rwUcPj",nameProduct: `simplehuman Kitchen Steel Frame Dish Rack With Swivel Spout, Fingerprint-Proof Stainless Steel Frame, Grey Plastic`,slug: ""},
			B07CPW4BXH: {href: "https://amzn.to/3fl3MSN",nameProduct: `Sweetnight King Mattress in a Box - 12 Inch Plush Pillow Top Hybrid Mattress, Gel Memory Foam for Sleep Cool, Motion Isolating Individually Wrapped Coils, King Size, Twilight`,slug: ""},
			B07GGF5RFF: {href: "https://amzn.to/3syW6A8",nameProduct: `Zinus Josh Traditional Upholstered 77.5 Inch Sofa/Living Room Couch, Beige Weave`,slug: ""},
			B01DD6C4TC: {href: "https://amzn.to/2PyCbmy",nameProduct: `Mr. Heater F274830 MH18BRV Big Buddy Grey Indoor-Safe Portable RV Propane Heater (4,000 , 9,000 and 18,000 BTU)`,slug: ""},
			B00EUKHACW: {href: "https://amzn.to/3diijfH",nameProduct: `Shark Rocket Ultra-Light Corded Bagless Vacuum for Carpet and Hard Floor Cleaning with Swivel Steering and Car Detail Set (HV302), Gray/Orange`,slug: ""},
			B07T2G5Q6B: {href: "https://amzn.to/2QAn2Bt",nameProduct: `simplehuman, Black Stainless Steel 58 Liter / 15.3 Gallon Rectangular Voice and Motion Sensor Automatic Kitchen Trash Can`,slug: ""},
			B016WJWC0S: {href: "https://amzn.to/2PzgTVV",nameProduct: `Olee Sleep 10 Inch Gel Infused Layer Top Memory Foam Mattress Blue, Queen`,slug: ""},
			B07FPHDC32: {href: "https://amzn.to/3cvRxks",nameProduct: `Human Touch NOVO XT2 Massage Chair, One Size, Red`,slug: ""},
			B00H2RSA88: {href: "https://amzn.to/3tYtuRe",nameProduct: `Sleep Innovations Marley 10-inch Cooling Gel Memory Foam Mattress Bed in a Box, Made in the USA, King, White`,slug: ""},
			B00JH98GR4: {href: "https://amzn.to/2PdZMsL",nameProduct: `Shark Navigator Lift-Away Deluxe NV360 Upright Vacuum, Blue`,slug: ""},
			B002G51BZU: {href: "https://amzn.to/3tVEdvC",nameProduct: `Mr. Heater F232000 MH9BX Buddy 4,000-9,000-BTU Indoor-Safe Portable Propane Radiant Heater, Red-Black`,slug: ""},
			B01EAG9XLG: {href: "https://amzn.to/31tzlBM",nameProduct: `Sleep Innovations Shea 10-inch Memory Foam Mattress, Bed in a Box, Made in the USA, 10-Year Warranty - Queen Size`,slug: ""},
			B01ET84Y46: {href: "https://amzn.to/3fl2WFV",nameProduct: `Modway Aveline 8" Gel Infused Memory Foam Full Mattress With CertiPUR-US Certified Foam`,slug: ""},
			B07CN38M23: {href: "https://amzn.to/39lS6eJ",nameProduct: `Masterbuilt MB20071117 Digital Electric Smoker`,slug: ""},
			B07D2V7TMY: {href: "https://amzn.to/3w85qgM",nameProduct: `PORTABLE DIGITAL ICE MAKER MACHINE by Arctic-Pro with Ice Scoop, First Ice in 6-8 Minutes, 26 Pounds Daily, Great for Kitchens, Tailgating, Bars, Party, Small/Large Cubes, Silver, 11.5x8.7x12.5 Inch`,slug: ""},
			B07CWLRXBK: {href: "https://amzn.to/39p9ZcS",nameProduct: `HOFISH 10 Inch Medium Firm Gel-Infused Memory Foam Mattress - Ideal Support & Great Motion Isolation - CertiPUR-US Certified Foam - Medium Firm - Queen`,slug: ""},
			B07FP186CN: {href: "https://amzn.to/3w94tVc",nameProduct: `TOTO MS900CUMFG#01 Neorest NX1 Electronic Dual Flush Toilet - Cotton White`,slug: ""},
			B0734CXX69: {href: "https://amzn.to/31rxtd2",nameProduct: `Zinus Dachelle Upholstered Button Tufted Premium Platform Bed / Mattress Foundation / Easy Assembly / Strong Wood Slat Support / Dark Grey, Full`,slug: ""},
			B00WNNYSJG: {href: "https://amzn.to/3lXBjUq",nameProduct: `UltraHD Tall Storage Cabinet - Stainless Steel`,slug: ""},
			B006MIUM20: {href: "https://amzn.to/3ryOQmC",nameProduct: `Zinus Shawn 14 Inch SmartBase Mattress Foundation / Platform Bed Frame / Box Spring Replacement / Quiet Noise-Free / Maximum Under-bed Storage, Queen`,slug: ""},
			B00CTTMDSC: {href: "https://amzn.to/3w6k9Zz",nameProduct: `Steelcase Amia Ergonomic Office Chair with Adjustable Back Tension and Arms | Flexible Lumbar with Sliding Seat | Black Frame and Buzz2 Pumpkin Fabric`,slug: ""},
			B07DWZK22R: {href: "https://amzn.to/3lWSNQS",nameProduct: `phiestina 46 Bottle Wine Cooler 24 Inch Dual Zone Built-in or Freestanding Wine Refrigerator with Compressor Cooling System`,slug: ""},
			B00BRUNPXQ: {href: "https://amzn.to/3lZKfsH",nameProduct: `Sauder August Hill L-Shaped Desk, Dover Oak finish`,slug: ""},
			B01EAG9X84: {href: "https://amzn.to/3u2jtTi",nameProduct: `Sleep Innovations Shiloh 12-inch Memory Foam Mattress, Bed in a Box, Quilted Cover, Made in The USA, 10-Year Warranty - Queen Size`,slug: ""},
			B010E9ILY8: {href: "https://amzn.to/3tZJcLP",nameProduct: `Sauder Edge Water Computer Desk, Auburn Cherry finish`,slug: ""},
			B07F3DP48S: {href: "https://amzn.to/3dbrwq1",nameProduct: `Intex 26333EH Ultra XTR Set Above Ground Pool, 20ft X 48in, Gray`,slug: ""},
			B07L7GGMH8: {href: "https://amzn.to/3dhiTdg",nameProduct: `LUNA Adult Weighted Blanket | 15 lbs - 60x80 - Queen Size Bed | 100% Oeko-Tex Certified Cooling Cotton & Premium Glass Beads | Designed in USA | Heavy Cool Weight for Hot & Cold Sleepers | Navy`,slug: ""},
			B004MXKUCY: {href: "https://amzn.to/3m0D6bf",nameProduct: `Simpson Cleaning MSH3125 MegaShot Gas Pressure Washer Powered by Honda GC190, 3200 PSI at 2.5 GPM`,slug: ""},
			B079W93GGX: {href: "https://amzn.to/3tXvut5",nameProduct: `Nespresso by De'Longhi EN500W Lattissima One Original Espresso Machine with Milk Frotherby De'Longhi, Silky White`,slug: ""},
			B00D4NPMJE: {href: "https://amzn.to/3fkUxlH",nameProduct: `Fuji 2202 Semi-PRO 2 HVLP Spray System, Blue`,slug: ""},
			B00BWYO53G: {href: "https://amzn.to/3rv4D5R",nameProduct: `Honeywell HPA300 True HEPA Air Purifier, Extra-Large Room, Black`,slug: ""},
			B089QNP5KC: {href: "https://amzn.to/3su8xgQ",nameProduct: `SYMA X500 4K Drone with UHD Camera for Adults, Easy GPS Quadcopter for Beginner with 56mins Flight Time, Brush Motor, 5GHz FPV Transmission, Auto Return Home, Follow Me, Light Positioning, 2 Batteries`,slug: ""},
			B07SY2Z5Y7: {href: "https://amzn.to/3rxHHTw",nameProduct: `Pulsar 12,000W Dual Fuel Portable Generator with Electric Start and Switch & Go Technology, CARB Approved PG12000B`,slug: ""},
			B077HW9XM7: {href: "https://amzn.to/2PwqHQm",nameProduct: `Ecovacs DEEBOT N79S Robotic Vacuum Cleaner with Max Power Suction, Upto 110 Min Runtime, Hard Floors and Carpets, Works with Alexa, App Controls, Self-Charging, Quiet`,slug: ""},
			B01DV3A8CC: {href: "https://amzn.to/3spZBcd",nameProduct: `Infinity IT-8500 X3 – Full Body Zero Gravity 3D Massage Chair – Featuring Air Compression, Decompression Stretch, Lumbar Heat, and Shiatsu Technique – Brown, Zero Gravity Chair, Massage Recliner Chair`,slug: ""},
			B07DTKXTXV: {href: "https://amzn.to/31ogN67",nameProduct: `Hoover Smartwash Automatic Carpet Cleaner, FH52000, Turquoise`,slug: ""},
			B00272N3DK: {href: "https://amzn.to/2QKvYV8",nameProduct: `Alera Valencia Series 60 by 30 by 29-1/2-Inch Desk Shell, Mahogany`,slug: ""},
			B009X43F38: {href: "https://amzn.to/3cu8YSJ",nameProduct: `Hobart 500559 Handler 140 MIG Welder 115V`,slug: ""},
			B005A4ON90: {href: "https://amzn.to/3w6utAM",nameProduct: `Signature Sleep Memoir 8-Inch Memory Foam Mattress, Queen Size`,slug: ""},
			B012J1TFTE: {href: "https://amzn.to/3tZ46ea",nameProduct: `Olee Sleep 13 inch Galaxy Hybrid Gel Infused Memory Foam and Pocket Spring Mattress (Queen)`,slug: ""},
			B07PWQF712: {href: "https://amzn.to/3dt5Iq7",nameProduct: `Colzer Portable Electronic Ice Maker Machine, Countertop Ice Maker,Make 9 Ice Cubes within 6-13 Minutes,33lbs Ice in 24 hours,Water Tank and Ice Scoop, Home,Kitchen,Bar,KTV (silver)`,slug: ""},
			B01M0N8256: {href: "https://amzn.to/3fieCsZ",nameProduct: `DuroMax XP12000EH Dual Fuel Portable Generator - 12000 Watt Gas or Propane Powered-Electric Start- Home Back Up & RV Ready, 50 State Approved,Blue and Black`,slug: ""},
			B01NAUZJPE: {href: "https://amzn.to/31rwPw0",nameProduct: `Rheem 240V Heating Chamber RTEX-13 Residential Tankless Water Heater`,slug: ""},
			B079L5D89G: {href: "https://amzn.to/3syXsLe",nameProduct: `Ficmax Ergonomic Gaming Chair Massage Computer Gaming Chair Reclining Racing Office Chair with Footrest High Back Gamer Chair for E-sports Large size Gaming Desk Chair with Headrest and Lumbar Support`,slug: ""},
			B01BMCWJ7G: {href: "https://amzn.to/39iBvIQ",nameProduct: `BedJet 3 Climate Comfort for Beds, Cooling Fan + Heating Air (Single Temp. Zone Any Size Bed or Mattress)`,slug: ""},
			B07GYZS4RJ: {href: "https://amzn.to/39nZFSh",nameProduct: `Stiebel Eltron Tankless Water Heater – Tempra 24 Plus – Electric, On Demand Hot Water, Eco, White, 20.2`,slug: ""},
			B07S864GPW: {href: "https://amzn.to/39lztIa",nameProduct: `Shark IQ Robot Self-Empty XL RV1001AE, Robotic Vacuum, IQ Navigation, Home Mapping, Self-Cleaning Brushroll, Wi-Fi Connected, Works with Alexa`,slug: ""},
			B007HIKQCK: {href: "https://amzn.to/3filtm8",nameProduct: `Bio Bidet BB-600 BioBidet BB600 Ultimate Advanced Bidet Toilet Seat, White, Elongated`,slug: ""},
			B008EYOPPU: {href: "https://amzn.to/2P5q7JF",nameProduct: `Cuisinart GR-150P1 GR-150 Griddler Deluxe, Brushed Stainless`,slug: ""},
			B0799Q45TT: {href: "https://amzn.to/3fpdZxE",nameProduct: `Black + Decker BPWM09W Portable Washer`,slug: ""},
			B06XNQ8QDW: {href: "https://amzn.to/3tYukNW",nameProduct: `STANLEY SLP2050 Electric Power Washer, Medium, Yellow`,slug: ""},
			B07GJR5M6L: {href: "https://amzn.to/39kYqU3",nameProduct: `ENKEEO Power Station 155 Wh Portable Charger Lithium Backup Battery Pack 110V 100W Solar Generator (Solar Panel Optional) AC Outlet USB DC Supply for Outdoors Camping Travel Fishing Hunting Emergency`,slug: ""},
			B07MMMYTV7: {href: "https://amzn.to/3rsltSP",nameProduct: `VETOMILE 200W Peak Solar Generator, 45000mAh Portable Power Station with Pure Sine Wave 110V AC Outlet 3 USB Ports, 2 DC Ports 150W Rated Power Supply Pack for CPAP Outdoor Camping Backup`,slug: ""},
			B07JCZKJYB: {href: "https://amzn.to/2P63vJ3",nameProduct: `COLZER 232 PPD Commercial Dehumidifier, Large Industrial Dehumidifier with Hose for Basements, Warehouse & Job Sites Clean-Up, Flood, Water Damage Restoration - Moisture Removal Up to 29 Gallons/Day`,slug: ""},
			B00HHO0IEU: {href: "https://amzn.to/3sxHq4l",nameProduct: `Intex 77in PureSpa Portable Bubble Massage Spa Set`,slug: ""},
			B08B8YQB99: {href: "https://amzn.to/3cukQUP",nameProduct: `Intex 28431E PureSpa Plus 85in x 25in Outdoor Portable Inflatable 6 Person Round Hot Tub Spa with 170 Bubble Jets, Built in Heater Pump, and 6 Type S1 Filter Replacement Cartridges`,slug: ""},
			B00NB3P98G: {href: "https://amzn.to/3fksvGY",nameProduct: `Coleman SaluSpa Inflatable Hot Tub Spa, Green & White`,slug: ""},
			B015W8E3J8: {href: "https://amzn.to/39mzlbd",nameProduct: `Intex 77in PureSpa Portable Bubble Massage Spa Set`,slug: ""},
			B082324K53: {href: "https://amzn.to/3w6v9WQ",nameProduct: `Intex 28431E PureSpa Plus 85in x 25in Outdoor Portable Inflatable 6 Person Round Hot Tub Spa with 170 Bubble Jets, Cover, LED Light, and Built in Heater Pump, Navy`,slug: ""},
			B003R28HWQ: {href: "https://amzn.to/3ruSLRs",nameProduct: `Breville JE98XL Juice Fountain Plus Centrifugal Juicer, Brushed Stainless Steel`,slug: ""},
			B0044BBOQK: {href: "https://amzn.to/3fl35sJ",nameProduct: `Kreg K4MS Jig Master System (K4MS)`,slug: ""},
			B00FAW4O0A: {href: "https://amzn.to/3swP1jN",nameProduct: `SoundAsleep Dream Series Air Mattress with ComfortCoil Technology & Internal High Capacity Pump - Queen Size`,slug: ""},
			B00Q7EPSHI: {href: "https://amzn.to/3sv96af",nameProduct: `Zinus Green Tea Memory Foam Mattress, Queen, White`,slug: ""},
			B01AWXC70U: {href: "https://amzn.to/2PvFJ8Z",nameProduct: `Intex 28409E PureSpa 6 Person Home Outdoor Inflatable Portable Heated Round Hot Tub Spa 85-inch x 28-inch with 170 Bubble Jets and Built in Heat Pump, Blue`,slug: ""},
			B01MSZ036Q: {href: "https://amzn.to/31p23nB",nameProduct: `Dyson V7 Motorhead Cordless Stick Vacuum Cleaner, Fuchsia (227591-01)`,slug: ""},
			B012YMY3ZE: {href: "https://amzn.to/3lYrh5y",nameProduct: `Bestway Paris AirJet Hot Tub, (6-Person)`,slug: ""},
			B073FKF9KN: {href: "https://amzn.to/3rDttAR",nameProduct: `Intex 15ft X 48in Easy Set Pool Set with Filter Pump, Ladder, Ground Cloth & Pool Cover`,slug: ""},
			B00PCGHJPQ: {href: "https://amzn.to/3dhkm3g",nameProduct: `Skywalker Trampolines 15 Foot Jump N Dunk Round Trampoline with Enclosure-Basketball`,slug: ""},
			B01IY813UU: {href: "https://amzn.to/2O0FpPf",nameProduct: `Snapper XD 82V MAX Electric Cordless 21" Push Lawn Mower, Battery and Charger Not Included`,slug: ""},
			B00HVF3JGO: {href: "https://amzn.to/3sq0NMJ",nameProduct: `A-iPower SUA12000E 12,000-Watt Gasoline Powered Generator with Electric Start, 12000 Watt, Red/Black`,slug: ""},
			B00DCCYD6U: {href: "https://amzn.to/3w96Gjs",nameProduct: `iRobot Braava 380t Advanced Robot Mop- Wet Mopping and Dry Sweeping Cleaning Modes, Large Spaces`,slug: ""},
			B07G3ZNK4Y: {href: "https://amzn.to/39ogJrh",nameProduct: `Vector Robot by Anki, A Home Robot Who Hangs Out & Helps Out, With Amazon Alexa Built-In`,slug: ""},
			B07H7L92QD: {href: "https://amzn.to/3ueCeTF",nameProduct: `PAXCESS Electric Pressure Washer 2150 PSI 1.85 GPM High Pressure Power Washer Machine with All-in-One Nozzle, Hose Reel, Detergent Tank Best for Cleaning Homes/Buildings/Cars, Decks, Driveways, Patios`,slug: ""},
			B00UHNM1R0: {href: "https://amzn.to/3suMKFJ",nameProduct: `BOSTITCH Pancake Air Compressor, Oil-Free, 6 Gallon, 150 PSI (BTFP02012)`,slug: ""},
			B06XFVQFP9: {href: "https://amzn.to/2NYUaBZ",nameProduct: `LG LW6017R 6,000 BTU 115V Window Air Conditioner`,slug: ""},
			B0026SR0FW: {href: "https://amzn.to/3rp4Rvm",nameProduct: `Graco Magnum 262800 X5 Stand Airless Paint Sprayer, Blue`,slug: ""},
			B01C9RIACG: {href: "https://amzn.to/3swPZwr",nameProduct: `Coway Airmega 400 Smart Air Purifier with 1,560 sq. ft. Coverage`,slug: ""},
			B00HQONFY6: {href: "https://amzn.to/3rwgOPM",nameProduct: `WEN 4214 12-Inch Variable Speed Drill Press,Orange`,slug: ""},
			B072PZ4LVN: {href: "https://amzn.to/2PfgmZ9",nameProduct: `Amazon Brand – Rivet Revolve Modern Upholstered Sofa Couch, 80"W, Grey Weave`,slug: ""},
			B01923E15A: {href: "https://amzn.to/2PEYVRB",nameProduct: `Avallon ABR241SGRH 140 Can 24" Built-In Beverage Cooler - Right Hinge`,slug: ""},
			B07GL7PNPQ: {href: "https://amzn.to/3w1O0m1",nameProduct: `Traeger Grills TFB88PZBO Pro Series 34 Pellet Grill and Smoker, 884 Sq. In. Cooking Capacity, Bronze`,slug: ""},
			B01D8DAYBA: {href: "https://amzn.to/2QMnaOz",nameProduct: `Winix 5300-2 Air Purifier with True HEPA, PlasmaWave and Odor Reducing Carbon Filter,Gray`,slug: ""},
			B0792BWMV4: {href: "https://amzn.to/3swQwyr",nameProduct: `Roborock Robot Vacuum and Mop with Adaptive Routing,Multi-Floor Mapping, Selective Room Cleaning, Super Strong Suction, Robotic Vacuum Cleaner Works with Alexa`,slug: ""},
			B01DE8PN10: {href: "https://amzn.to/3u0vsR1",nameProduct: `Leggett & Platt Prodigy 2.0 Adjustable Bed with 10" Gel Cool Mattresses (split king(2 twin xl matts))`,slug: ""},
			B07GXZ49DY: {href: "https://amzn.to/31rFUFe",nameProduct: `Kahuna Massage Chair LM-6800 Black`,slug: ""},
			B07FFMTW8X: {href: "https://amzn.to/2PzpCr9",nameProduct: `Tineco A11 Hero Cordless Lightweight Stick/Handheld Vacuum Cleaner, 450W Motor for Ultra Powerful Suction for Carpet, Hard Floor & Pet`,slug: ""},
			B00LIAP2ZY: {href: "https://amzn.to/3sw4XCR",nameProduct: `LG WM3997HWA Ventless 4.3 Cu. Ft. Capacity Steam Washer/Dryer Combination with TurboWash, TrueBalance Anti-Vibration System, NeveRust Stainless Steel Drum, Allergiene Cycle in White`,slug: ""},
			B01DLPUWL2: {href: "https://amzn.to/3crBxjF",nameProduct: `Black + Decker BPACT08WT Portable Air Conditioner, 8,000 BTU`,slug: ""},
			B01N1I9D6E: {href: "https://amzn.to/3rpb3n6",nameProduct: `WoodBridge T-0001 One Piece Toilet, Rectangle Button and Soft Closing Seat - Dual Flush, Elongated, Comfort Height, Water Sense, High-Efficiency`,slug: ""},
			B07RGM11L5: {href: "https://amzn.to/3u0xiBt",nameProduct: `Frigidaire 5,000 BTU 115V Window-Mounted Mini-Compact Air Conditioner with Mechanical Controls, White`,slug: ""},
			B0128T2HQK: {href: "https://amzn.to/2PyLrqO",nameProduct: `SmartBidet SB-1000 Electric Bidet Seat for Elongated Toilets with Remote Control- Electronic Heated Toilet Seat with Warm Air Dryer and Temperature Controlled Wash Functions (White)`,slug: ""},
			B08D3HW1MQ: {href: "https://amzn.to/3m0rlBR",nameProduct: `ECOTRIC Electric Powerful Bicycle 26“ Fat Tire Bike 500W 36V/12AH Battery EBike Moped Snow Beach Mountain Ebike Throttle & Pedal Assist`,slug: ""},
			B07J31T4NC: {href: "https://amzn.to/3lXJKPA",nameProduct: `Nod by Tuft & Needle, Adaptive Foam 8-Inch Mattress, Queen`,slug: ""},
			B06W54K29J: {href: "https://amzn.to/3w7VPX1",nameProduct: `LEVOIT Air Purifier for Home Large Room,Smoke and Odor Eliminator, H13 True HEPA Filter for Bedroom, Auto Mode & 12h Timer, Cleaners for Allergies and Pets, Mold Pollen Dust, LV-PUR131, White`,slug: ""},
			B076MK5MHY: {href: "https://amzn.to/3w8DskQ",nameProduct: `Seatcraft Anthem Home Theater Seating Leather Multimedia Power Recline Sofa with Fold-Down Table, Adjustable Powered Headrests, Storage, AC/USB and Wireless Charging and Cup Holders (Black)`,slug: ""},
			B07GNSHPBQ: {href: "https://amzn.to/3cwvvyl",nameProduct: `Dash DFAF455GBAQ01 Deluxe Electric Air Fryer + Oven Cooker with Temperature Control, Non-stick Fry Basket, Recipe Guide + Auto Shut Off Feature, 1700-Watt, 6 Quart, 6 qt, Aqua`,slug: ""},
			B00FLYWNYQ: {href: "https://amzn.to/3rvJjgs",nameProduct: `Instant Pot Duo 7-in-1 Electric Pressure Cooker, Sterilizer, Slow Cooker, Rice Cooker, Steamer, Saute, Yogurt Maker, and Warmer, 6 Quart, 14 One-Touch Programs`,slug: ""},
			B077VRX8TV: {href: "https://amzn.to/31nUb5C",nameProduct: `Dash DMW001CU Machine for Individual, Paninis, Hash Browns, & other Mini waffle maker, 4 inch, Copper`,slug: ""},
			B077HW9XM7: {href: "https://amzn.to/3cqzM6d",nameProduct: `Ecovacs n79s robot vacuum, Dark Brown`,slug: ""},
			B07GB3FNNV: {href: "https://amzn.to/3ruunzw",nameProduct: `Instant Pot Aura Multi-Use Programmable Slow Cooker, 6 Quart, No Pressure Cooking Functionality`,slug: ""},
			B07F2D81JN: {href: "https://amzn.to/3w6sRad",nameProduct: `Amarey A800 Robot Vacuum - Super Suction Robotic Vacuum Cleaner, Long Lasting, Timer Function, Self-Charging, Multiple Cleaning Modes, Amarey Robot Vacuum Cleaner for Pet Hair, Hard Floor, Carpet`,slug: ""},
			B01CS3J570: {href: "https://amzn.to/2QCnE9I",nameProduct: `Honeywell HL10CESWK, 10, 000 BTU, Black/White Portable Air Conditioner, 10,000`,slug: ""},
			B00JJ5I7GQ: {href: "https://amzn.to/2Pwzd1M",nameProduct: `Polaris F9550 Sport Robotic In-Ground Pool Cleaner`,slug: ""},
			B08NT4YBQ3: {href: "https://amzn.to/3szaBEb",nameProduct: `Essential Hot Tubs 67-Jets 2021 Syracuse Hot Tub, Seats 5-6, Espresso`,slug: ""},
			B003IBGL7O: {href: "https://amzn.to/3csbgl5",nameProduct: `Hayward HP21404T HeatPro In Ground 140,000 BTU Heat Pump`,slug: ""},
			B071VLNVMD: {href: "https://amzn.to/3dcCZFH",nameProduct: `Tempur-PedicTEMPUR-CloudLuxe Breeze 13.5-Inch Extra-Soft Cooling Foam Mattress, Queen, Made in USA, 10 Year Warranty`,slug: ""},
			B003145K3E: {href: "https://amzn.to/3w5OvLA",nameProduct: `Silverback 60" In-Ground Basketball Hoop, Adjustable Height Tempered Glass Backboard and Pro-style flex Rim`,slug: ""},
			B01D3FOIR4: {href: "https://amzn.to/39mwHSZ",nameProduct: `LG LW1216ER Window-Mounted Remote Control, 12,000 BTU 115V Air Conditioner, White`,slug: ""},
			B00QXIJSQU: {href: "https://amzn.to/39kq7w2",nameProduct: `Koldfront WAC8001W 8,000 BTU Window Air Conditioner with 3,500 BTU Heater and Remote`,slug: ""},
			B003CT55YW: {href: "https://amzn.to/3cuQaCU",nameProduct: `RabbitAir MinusA2 Ultra Quiet HEPA Air Purifier - Stylish, Efficient and Energy Star (SPA-700A, White, Odor Remover)`,slug: ""},
			B07D826M1Y: {href: "https://amzn.to/3csjR7m",nameProduct: `LG LW1817IVSM 18,000 BTU Dual Inverter Window Air Conditioner, 230V, Remote Control, White`,slug: ""},
			B008UHXUSO: {href: "https://amzn.to/3lZatLD",nameProduct: `Honeywell CO60PM Evaporative Air Cooler For Indoor & Outdoor Use, 1540 CFM - 15.9 Gallon Tank, White/Gray`,slug: ""},
			B074QWYM22: {href: "https://amzn.to/3fyF3eb",nameProduct: `LUCID L300 Bed Base-5 Minute Assembly-Dual USB Charging Stations-Head and Foot Incline-Wireless Remote Adjustable, Twin XL, Charcoal`,slug: ""},
			B002WKJ5ES: {href: "https://amzn.to/3fl2Gqh",nameProduct: `Hayward Goldline AQR15 AquaRite Electronic Salt Chlorination System for In-Ground Pools , 40,000-Gallon Cell`,slug: ""},
			B00UCIOWRM: {href: "https://amzn.to/3u2s0FO",nameProduct: `TOTO SW2034#01 C100 Electronic Bidet Toilet Cleansing Water, Heated Seat, Deodorizer, Warm Air Dryer, and PREMIST, Elongated, Cotton White`,slug: ""},
			B00UB9R4KO: {href: "https://amzn.to/31qokkP",nameProduct: `JuiceBox 32 Next Generation Smart Electric Vehicle (EV) Charging Station with WiFi - 32 amp Level 2 EVSE, 25-Foot Cable, UL and Energy Star Certified, Indoor/Outdoor Use (NEMA 14-50 Plug, Gray)`,slug: ""},
			B003OBUE5I: {href: "https://amzn.to/3dapTJe",nameProduct: `Weber Summit S-670 LP Gas Grill, 7370001`,slug: ""},
			B01KWSXEJI: {href: "https://amzn.to/3m36rlt",nameProduct: `Hudson Bay 6 Person 19 Jet Spa with Stainless Jets and 110V GFCI Cord Included`,slug: ""},
			B08NSPS9NH: {href: "https://amzn.to/3cux2ER",nameProduct: `Essential Hot Tubs 67-Jets 2021 Syracuse Hot Tub, Seats 5-6, Gray`,slug: ""},
			B08NT5NHP5: {href: "https://amzn.to/31qoM2v",nameProduct: `Essential Hot Tubs 30-Jets 2021 Adelaide Hot Tub, Seats 5-6, Espresso`,slug: ""},
			B00BTKAPUU: {href: "https://amzn.to/3csclJF",nameProduct: `Coway AP-1512HH Mighty Air Purifier with True HEPA and Eco Mode`,slug: ""},
			B01KGR2EUU: {href: "https://amzn.to/3rvf5u7",nameProduct: `Coway AP-1216L Tower Mighty Air Purifier with True Hepa & Auto Mode(Up To 330 Sq.Ft.),,White`,slug: ""},
			B0861HFYW1: {href: "https://amzn.to/3szrsa6",nameProduct: `LUCID 10 Inch 2020 Gel Memory Foam Mattress - Medium Plush Feel - CertiPUR-US Certified - Hypoallergenic Bamboo Charcoal, Queen`,slug: ""},
			B00CSGGUUS: {href: "https://amzn.to/2QDa6La",nameProduct: `Global Air 10,000 BTU Portable Air Conditioner Cooling /Fan with Remote Control in White`,slug: ""},
			B00MYWQL96: {href: "https://amzn.to/3u2hRc8",nameProduct: `Hessaire MC37M Portable Evaporative Cooler, 3100 Cubic Feet per Minute, Cools 950 Square Feet`,slug: ""},
			B004VGIGVY: {href: "https://amzn.to/3sxfy0b",nameProduct: `Germ Guardian True HEPA Filter Air Purifier with UV Light Sanitizer, Eliminates Germs, Filters Allergies, Pollen, Smoke, Dust Pet Dander, Mold Odors, Quiet 22 inch 4-in-1 Air Purifier for Home AC4825E`,slug: ""},
			B07RHQ61T4: {href: "https://amzn.to/3swIDJk",nameProduct: `Frigidaire, White Energy Star 8,000 BTU 115V Cool Connect Smart Window Air Conditioner with Wi-Fi Control`,slug: ""},
			B01L1TFG66: {href: "https://amzn.to/3fne70G",nameProduct: `Z Grills Wood Pellet Grill Smoker with 2020 Newest Digital Controls ,700 Cooking Area 8- in-1 Grill, Smoke, Bake, Roast, Braise ,Sear,Char-grill and BBQ for Outdoor`,slug: ""},
			B0744CTXW8: {href: "https://amzn.to/3u6rkiF",nameProduct: `Swiss Madison Well Made Forever SM-1T254 St. Tropez One Piece Toilet, 26.6 x 15 x 31 inches, Glossy White`,slug: ""},
			B003G45CKK: {href: "https://amzn.to/31rIoTW",nameProduct: `LIFE SMART 4 Person Plug & Play Square Hot Tub Spa with 13 Jets and Cover, Beige`,slug: ""},
			B00GPGKN4G: {href: "https://amzn.to/3cw5wXu",nameProduct: `Drive Medical SFSCOUT4 Spitfire Scout 4 Compact Travel Scooter, 4-Wheel, Red/Blue`,slug: ""},
			B005UKGLAS: {href: "https://amzn.to/3rqrOOF",nameProduct: `WEN 4210 Drill Press with Laser, 10-Inch`,slug: ""},
			B079JYSPJQ: {href: "https://amzn.to/3lYCvHe",nameProduct: `Ikea Original Ektorp Cover for Sofa with Chaise, 3-Seat Sectional (Cover Only (Nordvalla Dark Gray)`,slug: ""},
			B0789H2XBQ: {href: "https://amzn.to/3w446vf",nameProduct: `ROVSUN 10 LBS Portable Washing Machine with Twin Tub Electric Compact Mini Washer, Energy/Save Space, Laundry Spin Cycle w/Hose, Perfect for Home RV Camping Dorms College Room`,slug: ""},
			B08BPDTL1H: {href: "https://amzn.to/31rL7Ni",nameProduct: `Garatic Portable Compact Mini Twin Tub Washing Machine w/Wash and Spin Cycle, Built-in Gravity Drain, 13lbs Capacity For Camping, Apartments, Dorms, College Rooms, RV’s, Delicates`,slug: ""},
			B07HKXVQYC: {href: "https://amzn.to/3sBAYJS",nameProduct: `Giantex Portable Compact Full-Automatic Laundry 8 lbs Load Capacity Washing Machine Washer/Spinner W/Drain Pump`,slug: ""},
			B08V5341CD: {href: "https://amzn.to/39o9NKN",nameProduct: `Magic Chef - MCSTCW16W4 Stainless Steel 1.6 Cu. Ft. Compact Top-Load Washer, White`,slug: ""},
			B01JKDAN2M: {href: "https://amzn.to/3w5S0BI",nameProduct: `Pure Enrichment PureZone Air Purifier - 3 Stage Filtration Cleans 99.97% of Air Particles with True HEPA Filter + UV-C Sanitizer, Relieves Smoke, Dust, and Helps Alleviate Allergies Up to 200 sq ft:`,slug: ""},
			B071D58ZY5: {href: "https://amzn.to/3fpodOy",nameProduct: `LEVOIT Air Purifier for Home with True HEPA Filter, Air Cleaner for Allergies and Pets, Smokers, Dust, Pollen, Quiet Odor Eliminators for Bedroom with Optional Night Light, 2-Year Warranty, LV-H132`,slug: ""},
			B01D8DAYII: {href: "https://amzn.to/3w7ZO5V",nameProduct: `Winix 5500-2 Air Purifier with True HEPA, PlasmaWave and Odor Reducing Washable AOC Carbon Filter:`,slug: ""},
			B07HK8J2WJ: {href: "https://amzn.to/3csR42A",nameProduct: `NAKTO 26" City Electric Bicycle and Assisted Bicycle for Men with Removable 36V 10A Large Capacity Lithium Battery and Charger`,slug: ""},
			B00G7VNO86: {href: "https://amzn.to/2Peb3cz",nameProduct: `Germ Guardian HEPA Filter Air Purifier with UV Light Sanitizer, Eliminates Germs, Filters Allergies, Pollen, Smoke, Dust, Pet Dander, Mold, Odors, Quiet 4-in-1 Air Purifier for Desk and Office AC4100`,slug: ""},
			B00HZ12BWM: {href: "https://amzn.to/2PFTzpy",nameProduct: `NewAir Beverage Cooler 22 Bottle and 70 Can Capacity Dual Zone Built in Refrigerator for Soda Beer or Wine, AWB-400DB Stainless Steel`,slug: ""},
			B0875XQD7L: {href: "https://amzn.to/3ctIRv6",nameProduct: `NewAir NBC160SS00 Freestanding Beverage Fridge, 160 Can, Stainless Steel, 160 Can`,slug: ""},
			B0083H1JA2: {href: "https://amzn.to/39l8kFd",nameProduct: `NewAir Beverage Refrigerator Cooler with 90 Can Capacity - Mini Bar Beer Fridge with Right Hinge Glass Door - Cools to 34F - AB-850 - Stainless Steel`,slug: ""},
			B07T2FWL8Q: {href: "https://amzn.to/3m6UwmU",nameProduct: `Traeger TFB57GZEO Pro Series 575 Grill, Smoker, Square inches, Bronze`,slug: ""},
			B082N6BV3X: {href: "https://amzn.to/3figYrL",nameProduct: `Traeger Pellet Grills TFB30KLF Tailgater 20 Grill, Black`,slug: ""},
			B07GLK1NC2: {href: "https://amzn.to/3u0BOzV",nameProduct: `Traeger Grills Pro Series 22 Pellet Grill & Smoker | Bronze, Gen I, 572 Sq. In. Capacity | TFB57PZBO model`,slug: ""},
			B06XTNWVVV: {href: "https://amzn.to/3fml9Te",nameProduct: `Traeger Grills TFB65LZBC Texas Elite 34 Wood Pellet Grill & Smoker, 646 Sq. In. Cooking Capacity, Bronze,Black and Bronze`,slug: ""},
			B0822BKLR4: {href: "https://amzn.to/3fiheqJ",nameProduct: `Traeger Grills Ironwood 650 Wood Pellet Grill and Smoker with Alexa and WiFIRE Smart Home Technology - Black`,slug: ""},
			B07T2FWL8Q: {href: "https://amzn.to/3u60UO3",nameProduct: `Traeger TFB57GZEO Pro Series 575 Grill, Smoker, Square inches, Bronze`,slug: ""},
			B01HJATY32: {href: "https://amzn.to/39mhtNG",nameProduct: `Keter Unity XL Portable Outdoor Table and Storage Cabinet with Hooks for Grill Accessories-Stainless Steel Top for Patio Kitchen Island or Bar Cart, Espresso Brown`,slug: ""},
			B01DB8PX1S: {href: "https://amzn.to/2QMx7eT",nameProduct: `Need Computer Desk Office Desk 55 inches Folding Table Computer Table Workstation No Install Needed,Teak Black AC5BB-140X`,slug: ""},
			B073VBWKJZ: {href: "https://amzn.to/3cvtceY",nameProduct: `hOmeLabs 4,500 Sq. Ft Energy Star Dehumidifier for Extra Large Rooms and Basements`,slug: ""},
			B076QJNK8G: {href: "https://amzn.to/3dhGaMg",nameProduct: `Mealthy MultiPot 9-in-1 Programmable Pressure Cooker 6 Quarts with Stainless Steel Pot, Steamer Basket, instant access to recipe app. Pressure cook, slow cook, sauté, rice cooker, yogurt, steam`,slug: ""},
			B01DVQF6EY: {href: "https://amzn.to/3szuxXI",nameProduct: `Alesis Strike Pro Kit | Eleven-Piece Professional Electronic Drum Kit with Adjustable Mesh Heads, 110 kits and over 1600 multi-sampled instruments`,slug: ""},
			B01M8LDBZY: {href: "https://amzn.to/31t3eSI",nameProduct: `Winix True HEPA 6300-2 Air Cleaner with PlasmaWave Technology`,slug: ""},
			B018Q69604: {href: "https://amzn.to/3lZelMF",nameProduct: `Alen BreatheSmart FIT50, Smoke/Chemical, White`,slug: ""},
			B01M65AYN8: {href: "https://amzn.to/3tZfxm6",nameProduct: `ENVION - Therapure TPP220 Air Purifier Tower with Handle and HEPA Type Technology Filter (White)`,slug: ""},
			B084GKPZ4V: {href: "https://amzn.to/3dhuetQ",nameProduct: `Winix Air Cleaner with PlasmaWave Technology (C545)`,slug: ""},
			B01N43P6XN: {href: "https://amzn.to/3sI8pdq",nameProduct: `Winix Air Cleaner with PlasmaWave Technology (C535)`,slug: ""},
			B073V9MG3Y: {href: "https://amzn.to/39m7fwQ",nameProduct: `hOmeLabs 1,500 Sq. Ft Energy Star Dehumidifier for Medium to Large Rooms and Basements`,slug: ""},
			B0116W5B5O: {href: "https://amzn.to/31qjWlJ",nameProduct: `La-Z-Boy Delano Big & Tall Executive Office Chair | High Back Ergonomic Lumbar Support, Bonded Leather, Brown | 45833 model`,slug: ""},
			B005NASZG8: {href: "https://amzn.to/3datrv2",nameProduct: `Hoover Commercial Lightweight Backpack Vacuum, C2401,Black`,slug: ""},
			B016OIF2JU: {href: "https://amzn.to/3fnd9RV",nameProduct: `Steelcase Gesture Chair, Graphite`,slug: ""},
			B00I0ZGOZM: {href: "https://amzn.to/31sViBc",nameProduct: `APEC Water Systems ROES-50 Essence Series Top Tier 5-Stage Certified Ultra Safe Reverse Osmosis Drinking Water Filter System`,slug: ""},
			B01DEWZUG4: {href: "https://amzn.to/3fldJQd",nameProduct: `Panasonic Microwave Oven NN-SN686S Stainless Steel Countertop/Built-In with Inverter Technology and Genius Sensor, 1.2 Cubic Foot, 1200W`,slug: ""},
			B07CRLHMNC: {href: "https://amzn.to/3tV1VZ0",nameProduct: `Osaki OS-Pro Maestro 4D Zero Gravity Massage Chair with Heated Rollers, L-Track Design, Touch Screen Remote (Brown)`,slug: ""},
			B07S6M9BD9: {href: "https://amzn.to/2NYvz06",nameProduct: `ZENY Portable Washing Machine Compact Twin Tub Laundry Washing Machine 17.6lbs Capacity Mini Washer Spinner for Apartment RV Travelling,Semi-Automatic`,slug: ""},
			B08XQXRJ1C: {href: "https://amzn.to/3dc0MFU",nameProduct: `ZOKOP Full-Automatic Washing Machine Portable Compact Laundry Washer Spin with Drain Pump,10 programs 8 Water Level Selections with LED Display 10 Lbs Capacity, Gray`,slug: ""},
			B01728NLRG: {href: "https://amzn.to/3fqH77F",nameProduct: `Coway AP-1512HH White HEPA Air Purifier, 16.8 x 18.3 x 9.6`,slug: ""},
			B07X4HGVNB: {href: "https://amzn.to/3ftSOdK",nameProduct: `Mid Century Lounge Chair with Ottoman, Classic Lounge Chair - Top Grain Leather - Black Leather Wood Palisander Lounge Chair Replica`,slug: ""},
			B009QYC60S: {href: "https://amzn.to/3dnmx5G",nameProduct: `Zojirushi NP-NVC10 Induction Heating Pressure Cooker and Warmer, 5.5 Cup, Stainless Brown, Made in Japan`,slug: ""},
			B07C758PD2: {href: "https://amzn.to/2O7c59I",nameProduct: `Shure SE846-CL+BT1 Wireless Sound Isolating Earphones with Bluetooth Enabled Communication Cable, Clear`,slug: ""},
			B00H2VOSP8: {href: "https://amzn.to/2PNGlak",nameProduct: `Corentium Home Radon Detector by Airthings 223 Portable, Lightweight, Easy-to-Use, (3) AAA Battery Operated, USA Version, pCi/L`,slug: ""},
			B07F3QF4KX: {href: "https://amzn.to/3cEnS97",nameProduct: `Intex 18ft X 9ft X 52in Ultra XTR Rectangular Pool Set with Sand Filter Pump, Ladder, Ground Cloth & Pool Cover`,slug: ""},
			B073FKF9B5: {href: "https://amzn.to/3m7GSQm",nameProduct: `Intex 18ft X 52in Ultra Frame Pool Set with Sand Filter Pump, Ladder, Ground Cloth & Pool Cover`,slug: ""},
			B00OX5BC28: {href: "https://amzn.to/2O9gngX",nameProduct: `Intex 18ft X 9ft X 52in Ultra Frame Rectangular Pool Set with Sand Filter Pump, Ladder, Ground Cloth & Pool Cover`,slug: ""},
			B073FNDD9F: {href: "https://amzn.to/3sI9u5a",nameProduct: `Intex 24ft X 12ft X 52in Ultra Frame Rectangular Pool Set with Sand Filter Pump & Saltwater System, Ladder, Ground Cloth, Pool Cover, Maintenance Kit & Volleyball:`,slug: ""},
			B073FMDBLV: {href: "https://amzn.to/3cDLYRc",nameProduct: `Intex 32ft X 16ft X 52in Ultra Frame Rectangular Pool Set with Sand Filter Pump, Ladder, Ground Cloth and Pool Cover`,slug: ""},
			B07F3FTJCM: {href: "https://amzn.to/3rYhePc",nameProduct: `Intex 24ft X 12ft X 52in Ultra XTR Rectangular Pool Set with Sand Filter Pump, Ladder, Ground Cloth & Pool Cover`,slug: ""},
			B07GYSB13N: {href: "https://amzn.to/2PE981b",nameProduct: `Intex 15'8" x 49" Ultra Frame Above Ground Swimming Pool Set with Pump & Ladder`,slug: ""},
			B00OX5B8CW: {href: "https://amzn.to/3rQHgUt",nameProduct: `Intex 12ft x 30in Metal Frame Pool with Filter Pump`,slug: ""},
			B07F39F6Z5: {href: "https://amzn.to/3mtmrxl",nameProduct: `Intex 32ft X 16ft X 52in Ultra XTR Rectangular Pool Set with Sand Filter Pump & Saltwater System, Ladder, Ground Cloth, Pool Cover, Maintenance Kit & Volleyball`,slug: ""},
			B07PQW4KJ4: {href: "https://amzn.to/3dJHwQp",nameProduct: `Intex 26373EH 32ft x 16ft x 52in Ultra XTR Frame Above Ground Rectangular Swimming Pool Set with Sand Filter Pump, Ladder, Cover, & Maintenance Kit`,slug: ""},
			B073FKF9B5: {href: "https://amzn.to/31QJqcj",nameProduct: `Intex 18ft X 52in Ultra Frame Pool Set with Sand Filter Pump, Ladder, Ground Cloth & Pool Cover`,slug: ""},
			B07F3QF4KX: {href: "https://amzn.to/31TomBO",nameProduct: `Intex 18ft X 9ft X 52in Ultra XTR Rectangular Pool Set with Sand Filter Pump, Ladder, Ground Cloth & Pool Cover`,slug: ""},
			B07GYWW355: {href: "https://amzn.to/3dDOyG3",nameProduct: `Intex 26339EH Pool Set, 24ft X 52in, Gray`,slug: ""},
			B07YZ8QJ4P: {href: "https://amzn.to/3ut31eV",nameProduct: `Okaysou AirMic4S H13 HEPA Air Purifiers for Home Pets Hair Smokers with Washable Pre-filter, Timer, Night Light, Eliminates Smoke, Dust, Pollen, Pet Dander, VOCs, 300 Sq Ft, 100% Ozone Free`,slug: ""}
		}
	}
	return dataAMZ;
}
