function getData(){
	const keysw = "www.tipslittle.com";
	var keyAPI = (typeof keyhost != 'undefined') ? keyhost : document.location.host;
	var dataAMZ = {};
	if(keysw == keyAPI){
		dataAMZ = {
			B07YZ8QJ4P: {href: "https://amzn.to/3xwWKQX",nameProduct: `Okaysou AirMic4S Air Purifier with Medical Grade H13 True HEPA filter for Home, Remove Pet Hair, Smoke, Pollen, Dust, Pet Dander, VOCs, for Large/Small Room/ Desktop,White`,image: '',summary: ``,slug: ""},
			B077VRX8TV: {href: "https://amzn.to/2TPix7M",nameProduct: `Dash DMW001CU Mini Maker for Individual Waffles, Hash Browns, Keto Chaffles with Easy to Clean, Non-Stick Surfaces, 4 Inch, Copper`,image: '',summary: ``,slug: ""},
			B07R56HW4G: {href: "https://amzn.to/3gK76HI",nameProduct: `Euhomy Ice Maker Machine Countertop, 26 lbs in 24 Hours, 9 Cubes Ready in 6 Mins, Electric ice maker and Compact potable ice maker with Ice Scoop and Basket. Perfect for Home/Kitchen/Office.(Sliver)`,image: '',summary: ``,slug: ""},
			B07FSYZVTZ: {href: "https://amzn.to/2TUOFHj",nameProduct: `Smart Digital Manual Incline Treadmill - Slim Folding Electric 2.5 HP Indoor Home Foldable Fitness Exercise Running Machine with Downloadable App, MP3 Player, Safety Key - SereneLife SLFTRD25`,image: '',summary: ``,slug: ""},
			B07H2NP7PR: {href: "https://amzn.to/3wPoVKO",nameProduct: `Intex - 10' X 30" Prism Frame Premium Pool Set`,image: '',summary: ``,slug: ""},
			B076KKX4BC: {href: "https://amzn.to/3gM32qn",nameProduct: `Xiaomi Mi Electric Scooter, 18.6 Miles Long-range Battery, Up to 15.5 MPH, Easy Fold-n-Carry Design, Ultra-Lightweight Adult Electric Scooter (US Version with Warranty)`,image: '',summary: ``,slug: ""},
			B07PL6LDP1: {href: "https://amzn.to/35PxQ2V",nameProduct: `Sony HT-S350 Soundbar with Wireless Subwoofer: S350 2.1ch Sound Bar and Powerful Subwoofer - Home Theater Surround Sound Speaker System for TV - Blutooth and HDMI Arc Compatible Bar Black`,image: '',summary: ``,slug: ""},
			B07F39ZRCQ: {href: "https://amzn.to/3cZjXU8",nameProduct: `Bose Bass Module 700 - Black- Wireless, Compact Subwoofer`,image: '',summary: ``,slug: ""},
			B07QV8PMBY: {href: "https://amzn.to/2TUo6BO",nameProduct: `OOTORI 2020 New N500 Pro Massage Chair, Massage Chairs Recliner and Full Body, Zero Gravity Massage Chair, Airbags Shiatsu Massage Chair Recliner with Lower Back Heating, Hip Vibration and Foot Roller`,image: '',summary: ``,slug: ""},
			B0002KVQBA: {href: "https://amzn.to/2UhZR0C",nameProduct: `Polk Audio PSW10 10" Powered Subwoofer - Power Port Technology, Up to 100 Watts, Big Bass in Compact Design, Easy Setup with Home Theater Systems Black`,image: '',summary: ``,slug: ""},
			B002ZDAEIS: {href: "https://amzn.to/3vSYDGi",nameProduct: `Razor EcoSmart Metro Electric Scooter`,image: '',summary: ``,slug: ""},
			B004J2GUOU: {href: "https://amzn.to/3gWSkw4",nameProduct: `Coleman 2-Person Dome Tent for Camping | Sundome Tent with Easy Setup`,image: '',summary: ``,slug: ""},
			B0193V3DJ6: {href: "https://amzn.to/3zKPzqa",nameProduct: `NordicTrack T 6.5 Series`,image: '',summary: ``,slug: ""},
			B002KV1MJU: {href: "https://amzn.to/35JVUnX",nameProduct: `Marcy Recumbent Exercise Bike with Resistance ME-709`,image: '',summary: ``,slug: ""},
			B07FTN21JL: {href: "https://amzn.to/3zOe2Lq",nameProduct: `Fitbit Charge 3 Fitness Activity Tracker`,image: '',summary: ``,slug: ""},
			B01ALBMIEI: {href: "https://amzn.to/3x1B6Ek",nameProduct: `Giantex Portable Mini Compact Twin Tub Washing Machine 17.6lbs Washer Spain Spinner, Blue+ White`,image: '',summary: ``,slug: ""},
			B07144LZ9V: {href: "https://amzn.to/3zOqjzm",nameProduct: `Best Choice Products Portable Mini Twin Tub Compact Washing Machine and Dryer Combo, 18-Pound Load Capacity, w/ 15-Minute Timer, Drain Hose, Spin Dry Cycle, White/Blue`,image: '',summary: ``,slug: ""},
			B077HW9XM7: {href: "https://amzn.to/3d6E5U6",nameProduct: `Ecovacs DEEBOT N79S Robotic Vacuum Cleaner with Max Power Suction, Upto 110 Min Runtime, Hard Floors and Carpets, Works with Alexa, App Controls, Self-Charging, Quiet`,image: '',summary: ``,slug: ""},
			B002MPLYEW: {href: "https://amzn.to/2TYqHL1",nameProduct: `Danby 120 Can Beverage Center, Stainless Steel DBC120BLS`,image: '',summary: ``,slug: ""},
			B001EQ45OG: {href: "https://amzn.to/35N6SJk",nameProduct: `American Standard 2461002.011 Cambridge Apron-Front Americast Soaking Bathtub Right Hand Drain, 5 ft x 32 in, Arctic`,image: '',summary: ``,slug: ""},
			B00450U6CS: {href: "https://amzn.to/3d3dhEy",nameProduct: `Bissell Big Green Professional Carpet Cleaner Machine, 86T3`,image: '',summary: ``,slug: ""},
			B001CNG7RY: {href: "https://amzn.to/3j4Cdis",nameProduct: `DeLonghi EC702 15-Bar-Pump Espresso Maker, Stainless, Metal`,image: '',summary: ``,slug: ""},
			B074MLZR3Y: {href: "https://amzn.to/3wU2Tqo",nameProduct: `Brondell Swash Non-Electric Seat, Fits Round Toilets, White – Dual Nozzle System, Ambient Water Temperature – Bidet with Easy Installation`,image: '',summary: ``,slug: ""},
			B07Q7Y84S6: {href: "https://amzn.to/2SYmkQb",nameProduct: `Ecovacs DEEBOT 500 Robot Vacuum Cleaner with Max Power Suction, Up to 110 min Runtime, Hard Floors & Carpets, Pet Hair, App Controls, Self-Charging, Quiet, Large, Black`,image: '',summary: ``,slug: ""},
			B00PHNFML2: {href: "https://amzn.to/3qh9GIh",nameProduct: `Breville BFP660SIL Sous Chef 12 Cup Food Processor, Silver`,image: '',summary: ``,slug: ""},
			B00K150VAI: {href: "https://amzn.to/35HtI51",nameProduct: `Smittybilt (98510) X2O Waterproof Synthetic Rope Winch - 10000 lb. Load Capacity`,image: '',summary: ``,slug: ""},
			B005EFYCNW: {href: "https://amzn.to/3gWMACh",nameProduct: `Sauder Home Plus Storage Cabinet, Dakota Oak finish`,image: '',summary: ``,slug: ""},
			B07GYP68HW: {href: "https://amzn.to/2TT6Yg2",nameProduct: `Epson Home Cinema 4010 4K PRO-UHD (1) 3-Chip Projector with HDR`,image: '',summary: ``,slug: ""},
			B0144DQNWW: {href: "https://amzn.to/3j4ptJ0",nameProduct: `Ultra HD Mega Storage Cabinet - Stainless Steel`,image: '',summary: ``,slug: ""},
			B075FGY7G2: {href: "https://amzn.to/35GnmDc",nameProduct: `Zinus Suzanne Metal and Wood Platform Bed with Headboard / Box Spring Optional / Wood Slat Support, Queen`,image: '',summary: ``,slug: ""},
			B07B94ZR74: {href: "https://amzn.to/2SWPuz6",nameProduct: `SUPER DEAL Portable Washer Mini Twin Tub Washing Machine 17.6 lbs w/78.8'' Inlet Hose`,image: '',summary: ``,slug: ""},
			B01B8DGNMQ: {href: "https://amzn.to/3d0R0aj",nameProduct: `Prodigy 2.0 Leggett & Platt Adjustable Bed Base`,image: '',summary: ``,slug: ""},
			B0067MQM48: {href: "https://amzn.to/3zMzBMe",nameProduct: `Zojirushi BB-PAC20BA BB-PAC20 Home Bakery Virtuoso Breadmaker with Gluten Free Menu setting`,image: '',summary: ``,slug: ""},
			B00C1EJPJA: {href: "https://amzn.to/3zPJuJ7",nameProduct: `Zodiac MX8 Suction-Side Cleaner`,image: '',summary: ``,slug: ""},
			B01MXIMVXG: {href: "https://amzn.to/3d5LH9q",nameProduct: `ASICS Men's Gel-Venture 6 Running Shoe`,image: '',summary: ``,slug: ""},
			B074FKGR7F: {href: "https://amzn.to/3d5LRh2",nameProduct: `Epson Home Cinema 2100 1080p 3LCD projector`,image: '',summary: ``,slug: ""},
			B003PCSR82: {href: "https://amzn.to/3zQk9i7",nameProduct: `EdgeStar AP14001HS Portable Air Conditioner and Heater with Dehumidifier and Fan for Rooms up to 525 Sq. Ft. with Remote Control`,image: '',summary: ``,slug: ""},
			B07VPL2HYG: {href: "https://amzn.to/2UlKq7G",nameProduct: `YnM Weighted Blanket 3 Pieces Set with 2 Duvet Covers | Suit for Hot & Cold Sleepers Year Round Use (60''x 80'' 20lbs)`,image: '',summary: ``,slug: ""},
			B01B8GQ940: {href: "https://amzn.to/2SVjNWM",nameProduct: `Zinus Mia Modern Studio 14 Inch Platform 1500H Metal Bed Frame / Mattress Foundation / Wooden Slat Support / With Headboard / Good Design Award Winne`,image: '',summary: ``,slug: ""},
			B07XF9NYV3: {href: "https://amzn.to/3xLtEgU",nameProduct: `Zmodo 1080p Full HD Outdoor Wireless Security Camera System, 4 Pack Smart Home Indoor Outdoor WiFi IP Cameras with Night Vision, Compatible with Alexa`,image: '',summary: ``,slug: ""},
			B000XRQUSQ: {href: "https://amzn.to/2UwpbAg",nameProduct: `Krinner Tree Genie Tree Genie XXL Christmas Tree Stand, Green`,image: '',summary: ``,slug: ""},
			B002EKUK2C: {href: "https://amzn.to/3zOMYvs",nameProduct: `EdgeStar AP12000HS Portable Air Conditioner and Heater with Dehumidifier and Fan for Rooms up to 425 Sq. Ft. with Remote Control`,image: '',summary: ``,slug: ""},
			B00YEYKK8U: {href: "https://amzn.to/2T06bK3",nameProduct: `OXO BREW 9 Cup Coffee Maker`,image: '',summary: ``,slug: ""},
			B07B42DWWC: {href: "https://amzn.to/3d557LO",nameProduct: `Nectar Queen Mattress + 2 Pillows Included - Gel Memory Foam - CertiPUR-US Certified Foams - 180 Night Home Trial - Forever Warranty`,image: '',summary: ``,slug: ""},
			B076CPZWR3: {href: "https://amzn.to/35LB3ke",nameProduct: `Sauder HomePlus Storage Cabinet`,image: '',summary: ``,slug: ""},
			B00T9RANUC: {href: "https://amzn.to/3j7b1zU",nameProduct: `FLIR C2 - Compact Thermal Camera`,image: '',summary: ``,slug: ""},
			B00JXS3BXI: {href: "https://amzn.to/3d2asDl",nameProduct: `Smittybilt 9500 lb 97495 XRC GEN2 Winch-9500 Pound Load Capacity`,image: '',summary: ``,slug: ""},
			B06Y3LV4P5: {href: "https://amzn.to/2U2XKgZ",nameProduct: `PetChatz HD/PawCall Bundle`,image: '',summary: ``,slug: ""},
			B071FN6KXK: {href: "https://amzn.to/3zZhOSi",nameProduct: `Osmo Genius Kit for iPad`,image: '',summary: ``,slug: ""},
			B06WGLM9V1: {href: "https://amzn.to/3vR43BD",nameProduct: `Keenz 7s Stroller Wagon (Grey)`,image: '',summary: ``,slug: ""},
			B07MSYTQNM: {href: "https://amzn.to/2U2qOFG",nameProduct: `Fitbit Inspire HR Heart Rate & Fitness Tracker`,image: '',summary: ``,slug: ""},
			B00CMREO0Q: {href: "https://amzn.to/2TYBWU2",nameProduct: `Touchstone 80001 - Onyx Electric Fireplace - (Black) - 50 Inch Wide - On-Wall Hanging - Log & Crystal Included - 5 Flame Settings - Realistic Flame - 1500/750W Timer & Remote`,image: '',summary: ``,slug: ""},
			B00G0PF4FU: {href: "https://amzn.to/3vUC0kL",nameProduct: `Whynter 8,000 BTU Eco-Friendly Portable Air Conditioner, White (ARC-08WB)`,image: '',summary: ``,slug: ""},
			B07V48X7HG: {href: "https://amzn.to/3wVXUp5",nameProduct: `LG LW1019IVSM Energy Star 9,500 BTU 115V Dual Inverter Window Air Conditioner with Wi-Fi Control, White`,image: '',summary: ``,slug: ""},
			B01LWA8J37: {href: "https://amzn.to/3w3y5Cx",nameProduct: `AlorAir Basement/Crawl space Dehumidifiers Removal 120 PPD (Saturation) 55 PPD (AHAM), 5 Years Warranty, HGV Defrosting, cETL, Epoxy Coating, up to 1,300 Sq. Ft, Remote Monitoring`,image: '',summary: ``,slug: ""},
			B00198CW7G: {href: "https://amzn.to/3xRnage",nameProduct: `Hayward SP2610X15 Super Pump 1.5 HP Pool Pump`,image: '',summary: ``,slug: ""},
			B01AA8WOAK: {href: "https://amzn.to/3zToT6L",nameProduct: `Whynter Elite ARC-122DS 12,000 BTU Dual Hose Portable Air Conditioner, Dehumidifier, Fan with Activated Carbon Filter plus Storage bag for Rooms up to 400 sq ft`,image: '',summary: ``,slug: ""},
			B0009RF7DY: {href: "https://amzn.to/3xNcJuc",nameProduct: `Shoprider Sunrunner 4 Wheel Scooter`,image: '',summary: ``,slug: ""},
			B075CQ86ZV: {href: "https://amzn.to/3dbiH00",nameProduct: `Chamberlain B970T Smart Garage Door Opener with Battery Backup - myQ Smartphone Controlled - Ultra Quiet, Strong Belt Drive and MAX Lifting Power, 1.25 HP, Wireless Keypad Included, Blue`,image: '',summary: ``,slug: ""},
			B01BMCWJ7G: {href: "https://amzn.to/3xMjYCL",nameProduct: `BedJet 3 Climate Comfort for Beds, Cooling Fan + Heating Air (Single Temp. Zone Any Size Bed or Mattress)`,image: '',summary: ``,slug: ""},
			B00GY2Z21U: {href: "https://amzn.to/2U3QIIT",nameProduct: `Homegear 1500W Infrared Electric Portable Space Heater Black + Remote Control`,image: '',summary: ``,slug: ""},
			B07L6LB6LR: {href: "https://amzn.to/35Qp7O4",nameProduct: `Brooks Men's Ghost 12`,image: '',summary: ``,slug: ""},
			B002FQIYBY: {href: "https://amzn.to/35OSrob",nameProduct: `Pentair 340039 SuperFlo High Performance Single Speed Pool Pump, 1½ Horsepower, 115/230 Volt, 1 Phase`,image: '',summary: ``,slug: ""},
			B071HP9PDR: {href: "https://amzn.to/2T6t52h",nameProduct: `AlorAir LGR 85 Pint Commercial Dehumidifier with Pump, cETL Listed, 5 Years Warranty Memory Starting, for Damage Restoration, Crawlspace and Basement Drying`,image: '',summary: ``,slug: ""},
			B072MLT6QW: {href: "https://amzn.to/3dbjiyM",nameProduct: `Dometic CFX 50W 12v Electric Powered Portable Cooler, Fridge Freezer`,image: '',summary: ``,slug: ""},
			B07H5RVVM6: {href: "https://amzn.to/3xSOMBW",nameProduct: `Black + Decker BPWM09W Portable Washer`,image: '',summary: ``,slug: ""},
			B06Y1BLFBN: {href: "https://amzn.to/3x8UCzb",nameProduct: `Frigidaire 12,000 BTU Cool Connect Smart Portable Air Conditioner, Rooms upto 550-Sq. Ft`,image: '',summary: ``,slug: ""},
			B00CLD39C0: {href: "https://amzn.to/3gVGALo",nameProduct: `Rowenta DW9280 Digital Display Steam Iron, Stainless Steel Soleplate, 1800-Watt, 400-Hole, Blue`,image: '',summary: ``,slug: ""},
			B07P98YKDW: {href: "https://amzn.to/35QaRVB",nameProduct: `AlorAir LGR 85 Pint Commercial Dehumidifier with Pump, cETL Listed, 5 Years Warranty Memory Starting, for Damage Restoration, Crawlspace and Basement Drying`,image: '',summary: ``,slug: ""},
			B07N4MXR77: {href: "https://amzn.to/3vUUMbK",nameProduct: `Casio Privia PX-S1000 Digital Piano - Black`,image: '',summary: ``,slug: ""},
			B06Y32FG2N: {href: "https://amzn.to/3zZ9Bxa",nameProduct: `Brondell Swash 1400 Luxury Bidet Toilet Seat, Fits Elongated Toilets, White – Bidet – Dual Stainless-Steel Nozzles with Sterilization, Warm Air Dryer, Ambient Nightlight`,image: '',summary: ``,slug: ""},
			B01N0KXNFX: {href: "https://amzn.to/2U6d7Wk",nameProduct: `Zinus 6 Inch Spring Twin Mattress 2 pack, Perfect for Bunk Beds / Trundle Beds / Day Beds (Set of 2)`,image: '',summary: ``,slug: ""},
			B00KA8YC6A: {href: "https://amzn.to/3h1f4uR",nameProduct: `Delonghi EC680M DEDICA 15-Bar Pump Espresso Machine, Stainless Steel`,image: '',summary: ``,slug: ""},
			B000N2YKQ0: {href: "https://amzn.to/3je3MWD",nameProduct: `De'Longhi ESAM3300 Super Automatic Espresso/Coffee Machine`,image: '',summary: ``,slug: ""},
			B00GMMYLXC: {href: "https://amzn.to/3zVLrni",nameProduct: `Alen BreatheSmart Classic Large Room Air Purifier, 1100 sqft. Big Coverage Area, HEPA Filter for Allergies, Pollen, Dust, Dander and Fur in Espresso`,image: '',summary: ``,slug: ""},
			B07NHQ4CXM: {href: "https://amzn.to/35RwXas",nameProduct: `LG OLED65C9PUA Alexa Built-in C9 Series 65" 4K Ultra HD Smart OLED TV`,image: '',summary: ``,slug: ""},
			B013I40R8E: {href: "https://amzn.to/3h49A2n",nameProduct: `Breville BPR700BSS Fast Slow Pro Multi Function Cooker, Brushed Stainless Steel`,image: '',summary: ``,slug: ""},
			B00MWTJ9OA: {href: "https://amzn.to/3d9oJ15",nameProduct: `Classic Brands Cool Ventilated Gel Memory Foam 12-Inch Mattress - Queen`,image: '',summary: ``,slug: ""},
			B007HIKQCK: {href: "https://amzn.to/3vSn8Dv",nameProduct: `Bio Bidet Ultimate BB-600 Advanced Bidet Toilet Seat, Elongated White. Easy DIY Installation, Luxury Features From Side Panel, Adjustable Heated Seat and Water. Dual Nozzle Has Posterior and Feminine Wash`,image: '',summary: ``,slug: ""},
			B001BMDFPS: {href: "https://amzn.to/3xRLIG5",nameProduct: `DuroMax XP4400E Gas Powered Portable Generator - 4400 Watt -Electric Start- Camping & RV Ready, 50 State Approved,Blue and Black`,image: '',summary: ``,slug: ""},
			B07D8QGJ5V: {href: "https://amzn.to/3qpOxM1",nameProduct: `Desire Life Yoga Headstand Bench - Stand Yoga Chair for Family, Gym - Wood and PU Pads - Relieve Fatigue and Build Up Body`,image: '',summary: ``,slug: ""},
			B006LY18O6: {href: "https://amzn.to/3x12in0",nameProduct: `Aqua2Go GD70orGD600 1 Pack Multipurpose Portable Spray Washer with 17 Ltr/4.5 Gal Water Tank, Up to 130.5 psi, Includes Rechargeable Battery`,image: '',summary: ``,slug: ""},
			B07FPY2GL8: {href: "https://amzn.to/35UbIoq",nameProduct: `Medical Breakthrough 6 v4 Recliner 3D Massage Chair | Zero Gravity with Heating | Deep Tissue Shiatsu Full Body Massager | Yoga Stretch | Pain Relief | Full Foot Massager | Perfect Luxury Gift (Black)`,image: '',summary: ``,slug: ""},
			B07GPXKN8Z: {href: "https://amzn.to/3jeMyIM",nameProduct: `Flume Water Monitor: Smart Home Water Monitoring to Detect Leaks & Track Water Usage in Real Time. Compatible with Alexa`,image: '',summary: ``,slug: ""},
			B01M7M9NXX: {href: "https://amzn.to/3vQShY4",nameProduct: `Zinus Shalini Upholstered Diamond Stitched Platform Bed / Mattress Foundation / Easy Assembly / Strong Wood Slat Support / Dark Grey, Queen`,image: '',summary: ``,slug: ""},
			B07GH8DNZN: {href: "https://amzn.to/2UFnWyM",nameProduct: `Calphalon Special Brew 10 Cup Coffee Maker, Dark Stainless Steel`,image: '',summary: ``,slug: ""},
			B01J664WSY: {href: "https://amzn.to/3h4BBXx",nameProduct: `Vornado VMH600 Whole Room Stainless Steel Heater with Auto Climate Control and Remote`,image: '',summary: ``,slug: ""},
			B07S864GPW: {href: "https://amzn.to/3jrYKX1",nameProduct: `Shark IQ Robot Vacuum with Self-Empty Base and Wi-Fi Home Mapping, with XL Capacity Dust Bin, in Black`,image: '',summary: ``,slug: ""},
			B016OIF2JU: {href: "https://amzn.to/3w2Zsww",nameProduct: `Steelcase Gesture Chair, Graphite`,image: '',summary: ``,slug: ""},
			B009QYC60S: {href: "https://amzn.to/2U3fCbI",nameProduct: `Zojirushi Induction Heating Pressure Rice Cooker & Warmer 1.0 Liter, Stainless Brown NP-NVC10`,image: '',summary: ``,slug: ""},
			B07FFMTW8X: {href: "https://amzn.to/3dgn2Pz",nameProduct: `Tineco A11 Master+ Cordless Stick Vacuum Cleaner, Ultra Powerful Suction, Multi-Surface Cleaning, Great for Pet Hair, Emerald Green`,image: '',summary: ``,slug: ""},
			B018S68U40: {href: "https://amzn.to/3xNHRd0",nameProduct: `WORX WG163 GT 3.0 20V PowerShare 12" Cordless String Trimmer & Edger`,image: '',summary: ``,slug: ""},
			B00SMNLF4M: {href: "https://amzn.to/3vXOxDW",nameProduct: `WEN 56200i Super Quiet 2000-Watt Portable Inverter Generator, CARB Compliant`,image: '',summary: ``,slug: ""},
			B0713TGHVM: {href: "https://amzn.to/3qr2CbU",nameProduct: `Essential Hot Tubs 11 Jets Integrity Rotationally Molded Hot Tub, Cobblestone`,image: '',summary: ``,slug: ""},
			B01MTG1U4G: {href: "https://amzn.to/3da6gSj",nameProduct: `Home and Garden Spas HG51T 6 Person 51 Outdoor Spa with Stainless Jets & Ozone, 82" x 82" x 35", Tuscan Sun`,image: '',summary: ``,slug: ""},
			B07GZN3QNZ: {href: "https://amzn.to/3h5ujCZ",nameProduct: `Inofia Sleeping 8 inch Hybrid Comfort Eurotop Innerspring Mattress- Plush Yet Supportive-Pressure Relief (Twin)`,image: '',summary: ``,slug: ""},
			B000RP6DCC: {href: "https://amzn.to/3gZ8IvO",nameProduct: `American Standard 2461002.021 Cambridge Apron-Front Americast Soaking Bathtub Right Hand Drain, 5 ft x 32 in, Bone`,image: '',summary: ``,slug: ""},
			B078MGY2CS: {href: "https://amzn.to/3deVSIK",nameProduct: `Giantex Full-Automatic Washing Machine Portable Compact 1.6 Cu.ft Laundry Washer Spin with Drain Pump, 10 programs 8 Water Level Selections with LED Display 12 Lbs Capacity`,image: '',summary: ``,slug: ""},
			B001AMRCDU: {href: "https://amzn.to/2UuQTNE",nameProduct: `Davis Instruments 6152 Vantage Pro2 Wireless Weather Station with Standard Radiation Shield and LCD Display Console`,image: '',summary: ``,slug: ""},
			B077N51CR2: {href: "https://amzn.to/3qs8Qsn",nameProduct: `Homall Single Recliner Chair Padded Seat PU Leather Living Room Sofa Recliner Modern Recliner Seat Club Chair Home Theater Seating (Black)`,image: '',summary: ``,slug: ""},
			B005GSPVHS: {href: "https://amzn.to/3dffJYu",nameProduct: `Panasonic NE-1054F Countertop Commercial Microwave Oven with 10 Programmable Memory, Touch Screen Control and Bottom Energy Feed, 1000W, 0.8 Cu. Ft. (Stainless Steel), 5"`,image: '',summary: ``,slug: ""},
			B079D3PN6W: {href: "https://amzn.to/3deZJpp",nameProduct: `Pentair IntelliFlo VSF - Variable Speed and Flow Pool Pump - 3 Horsepower, 230 Volts - 011056 - Energy Star Certified`,image: '',summary: ``,slug: ""},
			B01DVW6G42: {href: "https://amzn.to/3xNIVO2",nameProduct: `PIONEER Air Conditioner Pioneer Mini Split Heat Pump Minisplit Heatpump 12000 BTU-208/230 V`,image: '',summary: ``,slug: ""},
			B008IXRY6Y: {href: "https://amzn.to/3jeGAHZ",nameProduct: `bawell Platinum Alkaline Water Ionizer Machine`,image: '',summary: ``,slug: ""},
			B00MMV0R76: {href: "https://amzn.to/3h9MdV0",nameProduct: `Pleasant Hearth 50,000 BTU Cabinet Pellet Stove`,image: '',summary: ``,slug: ""},
			B01IU6RJYA: {href: "https://amzn.to/2UD7j6S",nameProduct: `Linenspa 8 Inch Memory Foam and Innerspring Hybrid Mattress - Medium-Firm Feel - Twin`,image: '',summary: ``,slug: ""},
			B0148NPH9I: {href: "https://amzn.to/2T6KOqr",nameProduct: `Logitech K380 Multi-Device Bluetooth Keyboard – Windows, Mac, Chrome OS, Android, iPad, iPhone, Apple TV Compatible – with FLOW Cross-Computer Control and Easy-Switch up to 3 Devices – Dark Grey`,image: '',summary: ``,slug: ""},
			B01M3U32IA: {href: "https://amzn.to/3jfoRQS",nameProduct: `Lucid 4" Folding Mattress & Sofa with Removable Indoor/Outdoor Fabric Cover, Twin XL`,image: '',summary: ``,slug: ""},
			B000N5H2XU: {href: "https://amzn.to/3de7UlT",nameProduct: `Mac Knife MTH-80 Professional Hollow Edge Chef's Knife, 8 Inch, Silver`,image: '',summary: ``,slug: ""},
			B009IJ2LM4: {href: "https://amzn.to/3jep46x",nameProduct: `TOTO SW573#01 S300e WASHLET Electronic Bidet Toilet Seat with EWATER+ Cleansing, Round, Cotton White`,image: '',summary: ``,slug: ""},
			B00SMBFZNG: {href: "https://amzn.to/3dhXB0i",nameProduct: `VIZIO SB2920-C6 29-Inch 2.0 Channel Sound Bar`,image: '',summary: ``,slug: ""},
			B076V5KDTP: {href: "https://amzn.to/3jgFrj0",nameProduct: `Britax Advocate ClickTight Anti-Rebound Bar Convertible Car Seat - 3 Layer Impact Protection - Rear & Forward Facing - 5 to 65 Pounds, Mosaic`,image: '',summary: ``,slug: ""},
			B076TM35WP: {href: "https://amzn.to/3jgzTVV",nameProduct: `Jovial Portable Folding Baby Stroller (Blue)`,image: '',summary: ``,slug: ""},
			B0786NGJX8: {href: "https://amzn.to/3qu3bBN",nameProduct: `The Twin+ (Zoe XL2) - Best Double Stroller - Everyday Twin Stroller with Umbrella`,image: '',summary: ``,slug: ""},
			B075GFLQ7K: {href: "https://amzn.to/3gZ9gTP",nameProduct: `Kenmore 31140 Pet Friendly Lightweight Bagged Upright Beltless Vacuum with Pet Handi-Mate, Triple HEPA, Telescoping Wand, 4-Position Height Adjustment, 3 Cleaning Tools and AAFA Certified-Blue/Silver`,image: '',summary: ``,slug: ""},
			B07F3QF4KX: {href: "https://amzn.to/3jgFIT4",nameProduct: `Intex 18ft X 9ft X 52in Ultra XTR Rectangular Pool Set with Sand Filter Pump, Ladder, Ground Cloth & Pool Cover`,image: '',summary: ``,slug: ""},
			B073FKF9B5: {href: "https://amzn.to/3gWWXas",nameProduct: `Intex 18ft X 52in Ultra Frame Pool Set with Sand Filter Pump, Ladder, Ground Cloth & Pool Cover`,image: '',summary: ``,slug: ""},
			B01FXC7JWQ: {href: "https://amzn.to/3di17Yy",nameProduct: `Furbo Dog Camera: Treat Tossing, Full HD Wifi Pet Camera and 2-Way Audio, Designed for Dogs, Compatible with Alexa (As Seen On Ellen)`,image: '',summary: ``,slug: ""},
			B07BKQ314N: {href: "https://amzn.to/3x502ek",nameProduct: `REC TEC Grills | RT-340 | Bundle | WiFi Enabled | Portable Wood Pellet Grill | Built in Meat Probes | Stainless Steel | 20lb Hopper | 2 Year Warranty | Hotflash Ceramic Ignition System`,image: '',summary: ``,slug: ""},
			B00FZM1PUM: {href: "https://amzn.to/3A2l4Mz",nameProduct: `Rowenta DG8520 Perfect Steam 1800-Watt Eco Energy Steam Iron Station Stainless Steel Soleplate, 400-Hole, Purple`,image: '',summary: ``,slug: ""},
			B00T31O22Y: {href: "https://amzn.to/3qtmQlq",nameProduct: `Rug Doctor Portable Spot Cleaner Vacuum, Small, Red`,image: '',summary: ``,slug: ""},
			B01M2CGHKM: {href: "https://amzn.to/3A2Mimh",nameProduct: `Drill / Driver, 1x P235 Impact Driver, 1x P118 Dual Chemistry Charger, 2x P102 18V Batteries, 1x Tool Bag)`,image: '',summary: ``,slug: ""},
			B07RZ9LZW7: {href: "https://amzn.to/3qrxRns",nameProduct: `Samsung MS11K3000AS 1.1 cu. ft. Countertop Microwave Oven with Sensor and Ceramic Enamel Interior Silver Sand (Renewed)`,image: '',summary: ``,slug: ""},
			B00YUPDUYE: {href: "https://amzn.to/2T9UVuE",nameProduct: `Schlage Sense Smart Deadbolt with Century Trim in Satin Nickel (BE479 CEN 619)`,image: '',summary: ``,slug: ""},
			B07CSH453C: {href: "https://amzn.to/2U4abcK",nameProduct: `Sealy EASE 2.0 ADJ MECH Bed Mattress Conventional, Twin, white`,image: '',summary: ``,slug: ""},
			B00GMCAM2G: {href: "https://amzn.to/3h4ZazA",nameProduct: `Duxtop 1800W Portable Induction Cooktop Countertop Burner, Black`,image: '',summary: ``,slug: ""},
			B005KMDV9A: {href: "https://amzn.to/2TdaNfZ",nameProduct: `Shark Navigator Lift-Away Professional NV356E`,image: '',summary: ``,slug: ""},
			B00FOUDF62: {href: "https://amzn.to/3diwL88",nameProduct: `Sleep Innovations Shiloh 12-inch Memory Foam Mattress, Bed in a Box, Quilted Cover, Made in The USA, 10-Year Warranty - Queen Size`,image: '',summary: ``,slug: ""},
			B00AEMGGU2: {href: "https://amzn.to/2T8rJ7a",nameProduct: `Sonos - Playbar Soundbar Wireless Speaker - Black`,image: '',summary: ``,slug: ""},
			B00FAW4O0A: {href: "https://amzn.to/3h9827o",nameProduct: `SoundAsleep Dream Series Air Mattress with ComfortCoil Technology & Internal High Capacity Pump - Queen Size`,image: '',summary: ``,slug: ""},
			B009FT54CQ: {href: "https://amzn.to/3gYAl9N",nameProduct: `Sun Joe SWJ800E 8-Inch 6.5-Amp Telescoping Electric Pole Chain Saw with Automatic Chain Lubrication System`,image: '',summary: ``,slug: ""},
			B07DD7P933: {href: "https://amzn.to/3qrUE2i",nameProduct: `Full Mattress, Sweetnight Full Size Mattress- 10 Inch Gel Memory Foam Mattresses with CertiPUR-US Certified for Back Pain Relief/Motion Isolation&Cool Sleep, Flippable Comfort from Soft to Medium Firm`,image: '',summary: ``,slug: ""},
			B00UCIOWRM: {href: "https://amzn.to/3gYqoZN",nameProduct: `TOTO SW2034#01 C100 WASHLET Electronic Bidet Toilet Seat with PreMist, Elongated, Cotton White`,image: '',summary: ``,slug: ""},
			B00UCIOX2Q: {href: "https://amzn.to/3hg7DAe",nameProduct: `TOTO SW2044#01 C200 WASHLET Electronic Bidet Toilet Seat with Premist and SoftClose Lid, Elongated, Cotton White`,image: '',summary: ``,slug: ""},
			B00FOUDF62: {href: "https://amzn.to/3h8hlo0",nameProduct: `Toto MS992CUMFG#01 Neorest 1.0 GPF and 0.8 GPF 700H Dual Flush Toilet, Cotton White`,image: '',summary: ``,slug: ""},
			B07B8W5NYD: {href: "https://amzn.to/2SBPRPn",nameProduct: `LG LP1217GSR 115V Portable Air Conditioner with Remote Control in Graphite Gray for Rooms up to 300-Sq. Ft. (Renewed)`,image: '',summary: ``,slug: ""},
			B07X9JW274: {href: "https://amzn.to/2SFETZk",nameProduct: `Shinco 10,000 BTU Portable Air Conditioners with Built-in Dehumidifier Function, Fan Mode, Quiet AC Unit Cools Rooms to 300 sq.ft, LED Display, Remote Control, Complete Window Mount Exhaust Kit`,image: '',summary: ``,slug: ""},
			B08Z3GD7KN: {href: "https://amzn.to/2SAyazF",nameProduct: `COSTWAY Compact Twin Tub Washing Machine, 17.6 lbs Mini Washing Machine with Washing and Spinning, Portable Washer for Camping, Apartments, and Dorms, Blue`,image: '',summary: ``,slug: ""},
			B01G7IKA1C: {href: "https://amzn.to/3hjlzt8",nameProduct: `Portable Washing Machine 17lbs Compact Twin Tub Washer and Dryer Combo for Apartments,Dorms,RV's,College Rooms,Camping`,image: '',summary: ``,slug: ""},
			B076QR4JJ6: {href: "https://amzn.to/3jsYKFW",nameProduct: `Bestway 197030 Power Steel Pool`,image: '',summary: ``,slug: ""}
		}
	}
	return dataAMZ;
}
